// src/components/tutoring/ProfileEditor.tsx
'use client';

import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, Save } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import { TUTOR_LEVELS, TUTOR_MODES, TUTOR_SUBJECTS, type TutorLevel, type TutorMode } from '@/lib/tutoring/config';
import type { TutorRow } from '@/lib/server/tutoring-admin';
import { Alert } from '@/components/ui/Alert';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { CheckboxRow, Chip, Hint, Input, Label, Textarea, labelClass } from '@/components/ui/Field';

const school = TUTOR_SUBJECTS.filter((s) => s.group === 'scuola');
const university = TUTOR_SUBJECTS.filter((s) => s.group === 'università');

const toggle = <T extends string>(list: T[], value: T): T[] => (list.includes(value) ? list.filter((v) => v !== value) : [...list, value]);

/** Prefilled from the existing profile, or from the account for a new one. */
function initialForm(tutor: TutorRow | null, user: Pick<User, 'email' | 'user_metadata'> | null) {
	const meta = (user?.user_metadata ?? {}) as Record<string, unknown>;
	return {
		firstName: tutor?.first_name ?? (typeof meta.first_name === 'string' ? meta.first_name : ''),
		lastName: tutor?.last_name ?? (typeof meta.last_name === 'string' ? meta.last_name : ''),
		headline: tutor?.headline ?? '',
		bio: tutor?.bio ?? '',
		subjects: tutor?.subjects ?? ([] as string[]),
		levels: tutor?.levels ?? ([] as TutorLevel[]),
		modes: tutor?.modes ?? ([] as TutorMode[]),
		city: tutor?.city ?? '',
		hourlyRate: tutor?.hourly_rate == null ? '' : String(tutor.hourly_rate),
		education: tutor?.education ?? '',
		years: String(tutor?.years_experience ?? 0),
		contactPhone: tutor?.contact_phone ?? '',
		contactEmail: tutor?.contact_email ?? user?.email ?? '',
		terms: false
	};
}

/** Create or edit the signed-in user's tutor profile. A new profile goes to review; edits to a published one go live within a few minutes. */
export function ProfileEditor({ tutor, user }: { tutor: TutorRow | null; user: Pick<User, 'email' | 'user_metadata'> | null }) {
	const router = useRouter();
	const isNew = !tutor;
	const [form, setForm] = useState(() => initialForm(tutor, user));
	const [state, setState] = useState<{ saving?: boolean; saved?: boolean; error?: string }>({});
	const set = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => setForm((f) => ({ ...f, [key]: value }));
	const text = (key: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => set(key, e.target.value as never);

	const submit = async (e: FormEvent) => {
		e.preventDefault();
		if (state.saving) return;
		setState({ saving: true });
		try {
			const response = await fetch('/api/tutoring/profile', {
				method: 'PUT',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					first_name: form.firstName,
					last_name: form.lastName,
					headline: form.headline,
					bio: form.bio,
					subjects: form.subjects,
					levels: form.levels,
					modes: form.modes,
					city: form.modes.includes('in_person') ? form.city : '',
					hourly_rate: form.hourlyRate === '' ? null : Number(form.hourlyRate),
					education: form.education,
					years_experience: Number(form.years || 0),
					contact_phone: form.contactPhone,
					contact_email: form.contactEmail,
					terms: form.terms
				})
			});
			const body = await response.json().catch(() => ({}));
			if (!response.ok) throw new Error(body.error ?? 'Salvataggio non riuscito. Riprova tra qualche minuto.');
			setState({ saved: true });
			router.refresh();
		} catch (err) {
			setState({ error: err instanceof Error ? err.message : 'Salvataggio non riuscito. Riprova tra qualche minuto.' });
		}
	};

	const chips = <T extends string>(items: { id: T; name: string }[], list: T[], key: 'subjects' | 'levels' | 'modes', label: string) => (
		<div className="flex flex-wrap gap-2" role="group" aria-label={label}>
			{items.map((item) => (
				<Chip key={item.id} on={list.includes(item.id)} onClick={() => set(key, toggle(list, item.id) as never)}>{item.name}</Chip>
			))}
		</div>
	);

	return (
		<div className="max-w-3xl">
			<header className="mb-6">
				<h1 className="text-3xl font-bold text-fg">{isNew ? 'Crea il tuo profilo tutor' : 'Il tuo profilo tutor'}</h1>
				<p className="mt-1 text-fg-muted">
					{isNew
						? 'Sul sito compaiono nome e iniziale del cognome, presentazione, materie, livelli e prezzo indicativo. Telefono ed email restano privati: li ricevono solo gli studenti che accetti.'
						: tutor?.status === 'pending'
							? 'Il profilo è in revisione: puoi modificarlo finché non è pubblicato.'
							: 'Le modifiche compaiono sul profilo pubblico entro pochi minuti.'}
				</p>
			</header>
			{state.saved && (
				<Alert tone="success" title="Profilo salvato" className="mb-6 rounded-2xl p-5">
					<p className="text-fg-muted">{tutor?.status === 'pending' || isNew ? 'Lo controlliamo a breve e ti avvisiamo via email quando è pubblico.' : 'Le modifiche sono online.'}</p>
					<Link href="/dashboard" className="mt-2 inline-flex items-center gap-1 text-sm font-medium text-accent-fg hover:underline">Vai al riepilogo <ArrowRight className="size-3.5" aria-hidden="true" /></Link>
				</Alert>
			)}
			<form onSubmit={submit} className="space-y-8" noValidate>
				<Card as="section" className="space-y-4 bg-surface/80 p-5 sm:p-6" aria-labelledby="chi-sei">
					<h2 id="chi-sei" className="text-lg font-semibold text-fg">Chi sei</h2>
					<div className="grid gap-4 sm:grid-cols-2">
						<div>
							<Label htmlFor="first_name">Nome</Label>
							<Input id="first_name" type="text" value={form.firstName} onChange={text('firstName')} autoComplete="given-name" required />
						</div>
						<div>
							<Label htmlFor="last_name">Cognome</Label>
							<Input id="last_name" type="text" value={form.lastName} onChange={text('lastName')} autoComplete="family-name" required />
							<Hint>Sul sito compare solo l&apos;iniziale.</Hint>
						</div>
					</div>
					<div>
						<Label htmlFor="headline">Presentazione in una riga</Label>
						<Input id="headline" type="text" value={form.headline} onChange={text('headline')} maxLength={120} placeholder="Es. Laureanda in Matematica, preparo alle verifiche di quarta e quinta" required />
						<Hint>{form.headline.length}/120</Hint>
					</div>
					<div>
						<Label htmlFor="bio">Presentazione</Label>
						<Textarea id="bio" value={form.bio} onChange={text('bio')} rows={6} maxLength={2000} required placeholder="Cosa studi o hai studiato, da quanto dai ripetizioni, come lavori con gli studenti. Un paragrafo vuoto separa i capoversi." />
						<Hint>{form.bio.length}/2000, almeno 40 caratteri.</Hint>
					</div>
					<div className="grid gap-4 sm:grid-cols-2">
						<div>
							<Label htmlFor="education">Formazione <span className="font-normal text-fg-subtle">(facoltativa)</span></Label>
							<Input id="education" type="text" value={form.education} onChange={text('education')} maxLength={120} placeholder="Es. Ingegneria informatica, Politecnico di Torino" />
						</div>
						<div>
							<Label htmlFor="years">Anni di ripetizioni</Label>
							<Input id="years" type="number" value={form.years} onChange={text('years')} min={0} max={50} step={1} />
						</div>
					</div>
				</Card>

				<Card as="section" className="space-y-5 bg-surface/80 p-5 sm:p-6" aria-labelledby="cosa-insegni">
					<h2 id="cosa-insegni" className="text-lg font-semibold text-fg">Cosa insegni</h2>
					<fieldset>
						<legend className={labelClass}>Materie <span className="font-normal text-fg-subtle">(fino a otto)</span></legend>
						<p className="mb-2 text-xs text-fg-subtle">Scuola</p>
						<div className="mb-3">{chips(school, form.subjects, 'subjects', 'Materie di scuola')}</div>
						<p className="mb-2 text-xs text-fg-subtle">Università</p>
						{chips(university, form.subjects, 'subjects', 'Materie universitarie')}
					</fieldset>
					<fieldset>
						<legend className={labelClass}>Livelli</legend>
						{chips(TUTOR_LEVELS, form.levels, 'levels', 'Livelli')}
					</fieldset>
					<fieldset>
						<legend className={labelClass}>Modalità</legend>
						{chips(TUTOR_MODES, form.modes, 'modes', 'Modalità')}
					</fieldset>
					<div className="grid gap-4 sm:grid-cols-2">
						{form.modes.includes('in_person') && (
							<div>
								<Label htmlFor="city">Città per le lezioni in presenza</Label>
								<Input id="city" type="text" value={form.city} onChange={text('city')} maxLength={60} autoComplete="address-level2" placeholder="Es. Bologna" />
							</div>
						)}
						<div>
							<Label htmlFor="hourly_rate">Prezzo orario indicativo <span className="font-normal text-fg-subtle">(facoltativo)</span></Label>
							<div className="relative">
								<Input id="hourly_rate" type="number" value={form.hourlyRate} onChange={text('hourlyRate')} min={5} max={200} step={0.5} placeholder="15" className="pr-12" />
								<span className="absolute right-3.5 top-1/2 -translate-y-1/2 text-sm text-fg-subtle">€/h</span>
							</div>
							<Hint>Il prezzo lo concordi con lo studente; qui serve solo a orientare.</Hint>
						</div>
					</div>
				</Card>

				<Card as="section" className="space-y-4 bg-surface/80 p-5 sm:p-6" aria-labelledby="contatti">
					<h2 id="contatti" className="text-lg font-semibold text-fg">Contatti privati</h2>
					<p className="text-sm text-fg-muted">Non compaiono sul profilo. Li inviamo allo studente solo quando accetti la sua richiesta.</p>
					<div className="grid gap-4 sm:grid-cols-2">
						<div>
							<Label htmlFor="contact_phone">Telefono</Label>
							<Input id="contact_phone" type="tel" value={form.contactPhone} onChange={text('contactPhone')} autoComplete="tel" inputMode="tel" placeholder="+39 333 123 4567" required />
						</div>
						<div>
							<Label htmlFor="contact_email">Email</Label>
							<Input id="contact_email" type="email" value={form.contactEmail} onChange={text('contactEmail')} autoComplete="email" />
						</div>
					</div>
				</Card>

				{isNew && (
					<CheckboxRow checked={form.terms} onChange={(e) => set('terms', e.target.checked)} required className="rounded-2xl bg-surface/80 p-4">
						Accetto i <Link href="/terms" className="text-accent-fg hover:underline">Termini</Link> e l&apos;<Link href="/privacy" className="text-accent-fg hover:underline">informativa privacy</Link>. I dati degli studenti che accetto mi vengono comunicati solo per organizzare le lezioni: li uso per quello, non li cedo e li cancello se le lezioni non si fanno. Dichiaro imposte e contributi sulle lezioni per conto mio.
					</CheckboxRow>
				)}
				{state.error && <Alert tone="error">{state.error}</Alert>}
				<Button type="submit" size="lg" loading={state.saving}>
					{!state.saving && <Save className="size-4" aria-hidden="true" />}
					{state.saving ? 'Salvataggio' : isNew ? 'Invia il profilo in revisione' : 'Salva le modifiche'}
				</Button>
			</form>
		</div>
	);
}

// src/routes/(app)/(tutor)/profile-editor/+page.svelte
<script lang="ts">
	import { CheckCircle2, Loader2, Save, ArrowRight } from 'lucide-svelte';
	import { invalidateAll } from '$app/navigation';
	import { TUTOR_LEVELS, TUTOR_MODES, TUTOR_SUBJECTS, type TutorLevel, type TutorMode } from '$lib/tutoring/config';

	import Seo from '$lib/components/seo/Seo.svelte';

	/**
	 * Create or edit the signed-in user's tutor profile. A new profile goes to
	 * review; edits to a published one go live within a few minutes.
	 */
	let { data } = $props();
	let tutor = $derived(data.tutor);
	let isNew = $derived(!tutor);

	let firstName = $state('');
	let lastName = $state('');
	let headline = $state('');
	let bio = $state('');
	let subjects = $state<string[]>([]);
	let levels = $state<TutorLevel[]>([]);
	let modes = $state<TutorMode[]>([]);
	let city = $state('');
	let hourlyRate = $state('');
	let education = $state('');
	let years = $state('0');
	let contactPhone = $state('');
	let contactEmail = $state('');
	let terms = $state(false);

	let saving = $state(false);
	let error = $state<string | null>(null);
	let saved = $state(false);

	// Prefill from the existing profile, or from the account for a new one.
	$effect(() => {
		const t = data.tutor;
		if (t) {
			firstName = t.first_name;
			lastName = t.last_name;
			headline = t.headline;
			bio = t.bio;
			subjects = [...t.subjects];
			levels = [...t.levels];
			modes = [...t.modes];
			city = t.city ?? '';
			hourlyRate = t.hourly_rate == null ? '' : String(t.hourly_rate);
			education = t.education ?? '';
			years = String(t.years_experience ?? 0);
			contactPhone = t.contact_phone ?? '';
			contactEmail = t.contact_email ?? '';
		} else {
			const meta = (data.user?.user_metadata ?? {}) as Record<string, unknown>;
			if (!firstName && typeof meta.first_name === 'string') firstName = meta.first_name;
			if (!lastName && typeof meta.last_name === 'string') lastName = meta.last_name;
			if (!contactEmail && data.user?.email) contactEmail = data.user.email;
		}
	});

	function toggle<T extends string>(list: T[], value: T): T[] {
		return list.includes(value) ? list.filter((v) => v !== value) : [...list, value];
	}

	const schoolSubjects = TUTOR_SUBJECTS.filter((s) => s.group === 'scuola');
	const universitySubjects = TUTOR_SUBJECTS.filter((s) => s.group === 'università');

	async function submit(event: SubmitEvent) {
		event.preventDefault();
		if (saving) return;
		saving = true;
		error = null;
		saved = false;
		try {
			const response = await fetch('/api/tutoring/profile', {
				method: 'PUT',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					first_name: firstName,
					last_name: lastName,
					headline,
					bio,
					subjects,
					levels,
					modes,
					city: modes.includes('in_person') ? city : '',
					hourly_rate: hourlyRate === '' ? null : Number(hourlyRate),
					education,
					years_experience: Number(years || 0),
					contact_phone: contactPhone,
					contact_email: contactEmail,
					terms
				})
			});
			const body = await response.json().catch(() => ({}));
			if (!response.ok) throw new Error(body.error ?? 'Salvataggio non riuscito. Riprova tra qualche minuto.');
			saved = true;
			await invalidateAll();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Salvataggio non riuscito. Riprova tra qualche minuto.';
		} finally {
			saving = false;
		}
	}

	const fieldClass =
		'w-full rounded-xl border border-zinc-500/25 bg-white dark:bg-zinc-950 px-3.5 py-2.5 text-zinc-900 dark:text-zinc-100 placeholder:text-zinc-400 focus:border-crimson-500 focus:ring-2 focus:ring-crimson-500/30 outline-none transition';
	const labelClass = 'block text-sm font-medium text-zinc-700 dark:text-zinc-300 mb-1';
	const hintClass = 'mt-1 text-xs text-zinc-500 dark:text-zinc-400';
	const chipClass = (on: boolean) =>
		`px-3 py-1.5 rounded-full text-sm font-medium border transition-colors ${on ? 'bg-crimson-600 border-crimson-600 text-white' : 'bg-white dark:bg-zinc-950 border-zinc-500/25 text-zinc-700 dark:text-zinc-300 hover:border-crimson-300 dark:hover:border-crimson-800'}`;
</script>

<Seo title={isNew ? 'Crea il profilo tutor | Sapiens' : 'Modifica il profilo tutor | Sapiens'} path="/profile-editor" noindex />

<div class="max-w-3xl">
	<header class="mb-6">
		<h1 class="text-3xl font-bold text-zinc-900 dark:text-zinc-100">{isNew ? 'Crea il tuo profilo tutor' : 'Il tuo profilo tutor'}</h1>
		<p class="mt-1 text-zinc-600 dark:text-zinc-400">
			{#if isNew}
				Sul sito compaiono nome e iniziale del cognome, presentazione, materie, livelli e prezzo indicativo. Telefono ed
				email restano privati: li ricevono solo gli studenti che accetti.
			{:else if tutor?.status === 'pending'}
				Il profilo è in revisione: puoi modificarlo finché non è pubblicato.
			{:else}
				Le modifiche compaiono sul profilo pubblico entro pochi minuti.
			{/if}
		</p>
	</header>

	{#if saved}
		<div class="mb-6 rounded-2xl border border-emerald-200 dark:border-emerald-900/50 bg-emerald-50 dark:bg-emerald-900/20 p-5 flex items-start gap-3" role="status">
			<CheckCircle2 class="size-6 text-emerald-600 dark:text-emerald-400 shrink-0" aria-hidden="true" />
			<div>
				<h2 class="font-semibold text-zinc-900 dark:text-zinc-100">Profilo salvato</h2>
				<p class="text-sm text-zinc-700 dark:text-zinc-300">
					{#if tutor?.status === 'pending'}
						Lo controlliamo a breve e ti avvisiamo via email quando è pubblico.
					{:else}
						Le modifiche sono online.
					{/if}
				</p>
				<a href="/dashboard" class="mt-2 inline-flex items-center gap-1 text-sm font-medium text-crimson-600 dark:text-crimson-400 hover:underline">Vai al riepilogo <ArrowRight class="size-3.5" aria-hidden="true" /></a>
			</div>
		</div>
	{/if}

	<form onsubmit={submit} class="space-y-8" novalidate>
		<section class="rounded-2xl border border-zinc-500/25 bg-white/80 dark:bg-zinc-950/60 p-5 sm:p-6 space-y-4" aria-labelledby="chi-sei">
			<h2 id="chi-sei" class="text-lg font-semibold text-zinc-900 dark:text-zinc-100">Chi sei</h2>
			<div class="grid sm:grid-cols-2 gap-4">
				<div>
					<label for="first_name" class={labelClass}>Nome</label>
					<input id="first_name" type="text" bind:value={firstName} autocomplete="given-name" required class={fieldClass} />
				</div>
				<div>
					<label for="last_name" class={labelClass}>Cognome</label>
					<input id="last_name" type="text" bind:value={lastName} autocomplete="family-name" required class={fieldClass} />
					<p class={hintClass}>Sul sito compare solo l'iniziale.</p>
				</div>
			</div>
			<div>
				<label for="headline" class={labelClass}>Presentazione in una riga</label>
				<input id="headline" type="text" bind:value={headline} maxlength="120" placeholder="Es. Laureanda in Matematica, preparo alle verifiche di quarta e quinta" required class={fieldClass} />
				<p class={hintClass}>{headline.length}/120</p>
			</div>
			<div>
				<label for="bio" class={labelClass}>Presentazione</label>
				<textarea id="bio" bind:value={bio} rows="6" maxlength="2000" required placeholder="Cosa studi o hai studiato, da quanto dai ripetizioni, come lavori con gli studenti. Un paragrafo vuoto separa i capoversi." class="{fieldClass} resize-y"></textarea>
				<p class={hintClass}>{bio.length}/2000, almeno 40 caratteri.</p>
			</div>
			<div class="grid sm:grid-cols-2 gap-4">
				<div>
					<label for="education" class={labelClass}>Formazione <span class="text-zinc-400 font-normal">(facoltativa)</span></label>
					<input id="education" type="text" bind:value={education} maxlength="120" placeholder="Es. Ingegneria informatica, Politecnico di Torino" class={fieldClass} />
				</div>
				<div>
					<label for="years" class={labelClass}>Anni di ripetizioni</label>
					<input id="years" type="number" bind:value={years} min="0" max="50" step="1" class={fieldClass} />
				</div>
			</div>
		</section>

		<section class="rounded-2xl border border-zinc-500/25 bg-white/80 dark:bg-zinc-950/60 p-5 sm:p-6 space-y-5" aria-labelledby="cosa-insegni">
			<h2 id="cosa-insegni" class="text-lg font-semibold text-zinc-900 dark:text-zinc-100">Cosa insegni</h2>
			<fieldset>
				<legend class={labelClass}>Materie <span class="text-zinc-400 font-normal">(fino a otto)</span></legend>
				<p class="text-xs text-zinc-500 dark:text-zinc-400 mb-2">Scuola</p>
				<div class="flex flex-wrap gap-2 mb-3" role="group" aria-label="Materie di scuola">
					{#each schoolSubjects as s (s.id)}
						<button type="button" aria-pressed={subjects.includes(s.id)} onclick={() => (subjects = toggle(subjects, s.id))} class={chipClass(subjects.includes(s.id))}>{s.name}</button>
					{/each}
				</div>
				<p class="text-xs text-zinc-500 dark:text-zinc-400 mb-2">Università</p>
				<div class="flex flex-wrap gap-2" role="group" aria-label="Materie universitarie">
					{#each universitySubjects as s (s.id)}
						<button type="button" aria-pressed={subjects.includes(s.id)} onclick={() => (subjects = toggle(subjects, s.id))} class={chipClass(subjects.includes(s.id))}>{s.name}</button>
					{/each}
				</div>
			</fieldset>
			<fieldset>
				<legend class={labelClass}>Livelli</legend>
				<div class="flex flex-wrap gap-2" role="group" aria-label="Livelli">
					{#each TUTOR_LEVELS as l (l.id)}
						<button type="button" aria-pressed={levels.includes(l.id)} onclick={() => (levels = toggle(levels, l.id))} class={chipClass(levels.includes(l.id))}>{l.name}</button>
					{/each}
				</div>
			</fieldset>
			<fieldset>
				<legend class={labelClass}>Modalità</legend>
				<div class="flex flex-wrap gap-2" role="group" aria-label="Modalità">
					{#each TUTOR_MODES as m (m.id)}
						<button type="button" aria-pressed={modes.includes(m.id)} onclick={() => (modes = toggle(modes, m.id))} class={chipClass(modes.includes(m.id))}>{m.name}</button>
					{/each}
				</div>
			</fieldset>
			<div class="grid sm:grid-cols-2 gap-4">
				{#if modes.includes('in_person')}
					<div>
						<label for="city" class={labelClass}>Città per le lezioni in presenza</label>
						<input id="city" type="text" bind:value={city} maxlength="60" autocomplete="address-level2" placeholder="Es. Bologna" class={fieldClass} />
					</div>
				{/if}
				<div>
					<label for="hourly_rate" class={labelClass}>Prezzo orario indicativo <span class="text-zinc-400 font-normal">(facoltativo)</span></label>
					<div class="relative">
						<input id="hourly_rate" type="number" bind:value={hourlyRate} min="5" max="200" step="0.5" placeholder="15" class="{fieldClass} pr-12" />
						<span class="absolute right-3.5 top-1/2 -translate-y-1/2 text-sm text-zinc-500">€/h</span>
					</div>
					<p class={hintClass}>Il prezzo lo concordi con lo studente; qui serve solo a orientare.</p>
				</div>
			</div>
		</section>

		<section class="rounded-2xl border border-zinc-500/25 bg-white/80 dark:bg-zinc-950/60 p-5 sm:p-6 space-y-4" aria-labelledby="contatti">
			<h2 id="contatti" class="text-lg font-semibold text-zinc-900 dark:text-zinc-100">Contatti privati</h2>
			<p class="text-sm text-zinc-600 dark:text-zinc-400">Non compaiono sul profilo. Li inviamo allo studente solo quando accetti la sua richiesta.</p>
			<div class="grid sm:grid-cols-2 gap-4">
				<div>
					<label for="contact_phone" class={labelClass}>Telefono</label>
					<input id="contact_phone" type="tel" bind:value={contactPhone} autocomplete="tel" inputmode="tel" placeholder="+39 333 123 4567" required class={fieldClass} />
				</div>
				<div>
					<label for="contact_email" class={labelClass}>Email</label>
					<input id="contact_email" type="email" bind:value={contactEmail} autocomplete="email" class={fieldClass} />
				</div>
			</div>
		</section>

		{#if isNew}
			<label class="flex items-start gap-3 rounded-2xl border border-zinc-500/25 bg-white/80 dark:bg-zinc-950/60 p-4 text-sm text-zinc-700 dark:text-zinc-300 cursor-pointer">
				<input type="checkbox" bind:checked={terms} required class="mt-0.5 rounded border-zinc-400 text-crimson-600 focus:ring-crimson-500" />
				<span>
					Accetto i <a href="/terms" class="text-crimson-600 dark:text-crimson-400 hover:underline">Termini</a> e l'<a href="/privacy" class="text-crimson-600 dark:text-crimson-400 hover:underline">informativa privacy</a>.
					I dati degli studenti che accetto mi vengono comunicati solo per organizzare le lezioni: li uso per quello, non
					li cedo e li cancello se le lezioni non si fanno. Dichiaro imposte e contributi sulle lezioni per conto mio.
				</span>
			</label>
		{/if}

		{#if error}
			<p class="rounded-xl border border-red-200 dark:border-red-900/50 bg-red-50 dark:bg-red-900/20 px-4 py-3 text-sm text-red-700 dark:text-red-300" role="alert">{error}</p>
		{/if}

		<div class="flex items-center gap-3">
			<button type="submit" disabled={saving} class="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-crimson-600 hover:bg-crimson-700 text-white font-semibold shadow-sm transition-colors disabled:opacity-60 disabled:cursor-not-allowed">
				{#if saving}
					<Loader2 class="size-4 animate-spin" aria-hidden="true" />
					Salvataggio
				{:else}
					<Save class="size-4" aria-hidden="true" />
					{isNew ? 'Invia il profilo in revisione' : 'Salva le modifiche'}
				{/if}
			</button>
		</div>
	</form>
</div>
