// src/app/admin/wiki/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { BookOpen, FileText, Layers, LibraryBig, PenLine, Sigma } from 'lucide-react';
import { pageMetadata } from '@/lib/seo/page-metadata';
import { getContentTree } from '@/lib/server/content';
import { nodePath, plainTitle, subviewPath, dbPath } from '@/lib/seo/slug';
import { countByType, type ContentNode } from '@/lib/utils/tree';
import { configs } from '@/lib/exercises/config';
import { Stat } from '@/components/ui/Badge';
import { Latex } from '@/components/ui/Latex';

export const metadata: Metadata = pageMetadata({ title: 'Wiki | Admin | Sapiens', path: '/admin/wiki' });

const link = 'rounded text-accent-fg hover:underline focus-ring';

/** One lesson row: the title and which of its sections exist. */
function Lesson({ chain }: { chain: ContentNode[] }) {
	const node = chain[chain.length - 1];
	const exercises = !!configs[dbPath(chain)];
	return (
		<li className="flex flex-wrap items-center gap-x-3 gap-y-1 py-1.5 text-sm">
			<Link href={nodePath(chain)} className={link}><Latex content={node.title} /></Link>
			<span className="flex items-center gap-2 text-xs text-fg-subtle">
				<span className={node.has_theory ? 'text-ok-fg' : ''} title="Teoria"><BookOpen className="size-3.5" aria-hidden="true" /></span>
				{exercises && <Link href={subviewPath(chain, 'exercises')} className="text-ok-fg" title="Esercizi"><PenLine className="size-3.5" aria-hidden="true" /></Link>}
				{node.has_formulary && <Link href={subviewPath(chain, 'formulary')} className="text-ok-fg" title="Formulario"><Sigma className="size-3.5" aria-hidden="true" /></Link>}
			</span>
		</li>
	);
}

/** The whole library as an outline, straight from the database, with a link to every public page. */
export default async function AdminWikiPage() {
	const tree = await getContentTree();
	const counts = countByType(tree);
	const withTheory = tree.flatMap((l) => l.children.flatMap((s) => s.children.flatMap((c) => c.children))).filter((t) => t.has_theory).length;
	return (
		<div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
			<header className="mb-8">
				<h1 className="mb-2 text-3xl font-bold text-fg">Wiki</h1>
				<p className="mb-4 text-fg-muted">Livelli, materie, capitoli e lezioni pubblicati nel database, con le sezioni già scritte in verde.</p>
				<div className="flex flex-wrap gap-3">
					<Stat icon={LibraryBig}>{counts.subject} materie</Stat>
					<Stat icon={Layers} color="text-teal-500">{counts.chapter} capitoli</Stat>
					<Stat icon={FileText} color="text-indigo-500">{counts.topic} lezioni</Stat>
					<Stat icon={BookOpen} color="text-emerald-500">{withTheory} con teoria</Stat>
				</div>
			</header>
			{tree.map((level) => (
				<section key={level.id} className="mb-10" aria-labelledby={`level-${level.id}`}>
					<h2 id={`level-${level.id}`} className="mb-3 text-2xl font-semibold text-fg">
						<Link href={nodePath([level])} className={link}>{level.title}</Link>
					</h2>
					<div className="grid gap-4 md:grid-cols-2">
						{level.children.map((subject) => (
							<div key={subject.id} className="rounded-2xl border border-edge bg-surface p-4">
								<h3 className="mb-2 font-semibold text-fg">
									<Link href={nodePath([level, subject])} className={link}>{plainTitle(subject.title)}</Link>
								</h3>
								{subject.children.map((chapter) => (
									<details key={chapter.id} className="group">
										<summary className="cursor-pointer list-none py-1 text-sm text-fg-muted marker:hidden">
											<Link href={nodePath([level, subject, chapter])} className={link}><Latex content={chapter.title} /></Link>
											<span className="ml-2 text-xs text-fg-subtle">{chapter.children.length} lezioni</span>
										</summary>
										<ul className="ml-3 border-l border-edge pl-3">
											{chapter.children.map((topic) => <Lesson key={topic.id} chain={[level, subject, chapter, topic]} />)}
										</ul>
									</details>
								))}
							</div>
						))}
					</div>
				</section>
			))}
		</div>
	);
}

// src/routes/(app)/(content)/wiki/+page.svelte
<script lang="ts">
	import { Home, BookOpen, LibraryBig, Layers, FileText } from 'lucide-svelte';
	import { fade, fly } from 'svelte/transition';

	import Breadcrumb from '$lib/components/ui/Breadcrumb.svelte';
    import NodeCard from '$lib/components/ui/cards/NodeCard.svelte';

    let { data } = $props();
    let { 
        tree,
		analytics,
    } = $derived(data);

    let isLoading = $derived(!tree);

    let breadcrumbItems = $derived([
        { label: 'Home', path: '/', icon: Home },
        { label: 'Materiale didattico', path: '/wiki', icon: LibraryBig }
    ]);

	function getHref(node: { slug: string }) {
		return `/wiki/${node.slug}`;
	}
</script>

<svelte:head>
	<title>
		Contenuti didattici - Sapiens
	</title>
	<meta
		name="description"
		content="Esplora i contenuti didattici. Trova teoria, esercizi e risorse per tutte le materie disponibili."
	/>
</svelte:head>

<div class="min-h-screen bg-zinc-50 dark:bg-zinc-950 relative overflow-hidden">
	<div class="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
		{#if isLoading}
			<div class="flex justify-center items-center h-96">
				<div
					class="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-crimson-500"
				></div>
			</div>
		{:else}
			<header class="mb-12" in:fade={{ duration: 300 }}>
				<Breadcrumb items={breadcrumbItems} />

				<div class="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-8">
					<div class="flex items-start gap-6">
                        <div class="hidden sm:flex items-center justify-center size-32 rounded-2xl bg-white dark:bg-zinc-900 shadow-sm border border-zinc-500/25 text-crimson-500 dark:text-crimson-400">
                            <LibraryBig class="size-16" />
                        </div>

						<div class="flex-1 space-y-4">
							<div class="space-y-2">
								<div class="flex items-center gap-3">
                                    <LibraryBig class="w-8 h-8 text-crimson-500 dark:text-crimson-400 sm:hidden" />
									<h1 class="text-4xl sm:text-5xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
										Materiale didattico
									</h1>
								</div>
								<p class="text-lg text-zinc-600 dark:text-zinc-400 max-w-2xl leading-relaxed">
									Esplora i contenuti didattici disponibili per questo livello. Trova teoria,
									esercizi e risorse per tutte le materie.
								</p>
							</div>

							<div class="flex flex-wrap gap-3">
								<div class="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/80 dark:bg-zinc-900/80 border border-zinc-500/25 text-sm text-zinc-700 dark:text-zinc-300 backdrop-blur-sm">
									<BookOpen class="w-4 h-4 text-rose-500" />
									<span class="font-medium">{analytics["subject"]} Materie</span>
								</div>
								<div class="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/80 dark:bg-zinc-900/80 border border-zinc-500/25 text-sm text-zinc-700 dark:text-zinc-300 backdrop-blur-sm">
									<Layers class="w-4 h-4 text-teal-500" />
									<span class="font-medium">{analytics["chapter"]} Capitoli</span>
								</div>
									<div class="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/80 dark:bg-zinc-900/80 border border-zinc-500/25 text-sm text-zinc-700 dark:text-zinc-300 backdrop-blur-sm">
										<FileText class="w-4 h-4 text-indigo-500" />
										<span class="font-medium">{analytics["topic"]} Lezioni</span>
									</div>
							</div>
						</div>
					</div>
				</div>
			</header>

			<!-- Levels Grid -->
			{#if tree.length > 0}
				<section class="space-y-6" in:fade={{ duration: 400, delay: 100 }}>
					<div class="flex items-center justify-between border-b border-zinc-500/25 pb-4">
						<h2 class="text-2xl font-semibold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
							<BookOpen class="w-5 h-5 text-crimson-500" />
							Livelli didattici disponibili
						</h2>
					</div>

					<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
						{#each tree as node, index (node.id)}
							<div in:fly={{ y: 20, duration: 400, delay: index * 50 }} class="h-full">
								<NodeCard
									node={node}
									href={getHref(node)}
								/>
							</div>
						{/each}
					</div>
				</section>
			{/if}
		{/if}
	</div>
</div>
