// src/lib/components/landing/MobileMenu.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { afterNavigate } from '$app/navigation';
	import {
		House,
		LibraryBig,
		UsersRound,
		CreditCard,
		CircleHelp,
		Mail,
		LogIn,
		UserPlus,
		UserRound,
		ChevronRight
	} from 'lucide-svelte';
	import type { IconComponent } from '$lib/utils/icons';
	import { authState } from '$lib/state/auth.svelte';
	import { isStaff } from '$lib/auth/entitlements';
	import { CONTENT_ROOT, TUTORING_ROOT } from '$lib/config/site';
	import { nodePath } from '$lib/seo/slug';
	import type { ContentNode } from '$lib/utils/tree';

	import Sheet from '$lib/components/ui/Sheet.svelte';
	import ThemeToggle from '$lib/components/ui/theme/ThemeToggle.svelte';
	import LogoutButton from '$lib/components/ui/buttons/LogoutButton.svelte';

	/** The phone menu: every section of the site, the theme and the account, in one sheet. */
	let { open = $bindable(false) } = $props();

	// The content tree is loaded by the /materiale routes only; elsewhere the
	// menu links to the library without listing the levels.
	let tree = $derived((page.data.tree ?? []) as ContentNode[]);
	let pathname = $derived(page.url.pathname);
	let accountUrl = $derived(isStaff(authState.user) ? '/admin' : '/subscription');

	afterNavigate(() => (open = false));

	const close = () => (open = false);

	function login(register = false) {
		close();
		authState.openModal({ register });
	}

	const rowClass = (active: boolean) =>
		`flex min-h-[48px] items-center gap-3 rounded-xl px-3 text-base font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500 ${
			active
				? 'bg-crimson-50 text-crimson-700 dark:bg-crimson-900/30 dark:text-crimson-200'
				: 'text-zinc-800 hover:bg-zinc-100 active:bg-zinc-100 dark:text-zinc-100 dark:hover:bg-zinc-800 dark:active:bg-zinc-800'
		}`;

	let links = $derived<{ href: string; label: string; icon: IconComponent; active: boolean }[]>([
		{ href: '/', label: 'Home', icon: House, active: pathname === '/' },
		{ href: CONTENT_ROOT, label: 'Materiale didattico', icon: LibraryBig, active: pathname.startsWith(CONTENT_ROOT) },
		{ href: TUTORING_ROOT, label: 'Ripetizioni', icon: UsersRound, active: pathname.startsWith(TUTORING_ROOT) },
		{ href: '/pricing', label: 'Prezzi e abbonamenti', icon: CreditCard, active: pathname.startsWith('/pricing') },
		{ href: '/faq', label: 'Domande frequenti', icon: CircleHelp, active: pathname === '/faq' },
		{ href: '/contacts', label: 'Contatti', icon: Mail, active: pathname === '/contacts' }
	]);
</script>

<Sheet {open} onClose={close} title="Menu" bodyClass="px-3 pb-3">
	<nav aria-label="Menu" class="flex flex-col gap-0.5">
		{#each links as link (link.href)}
			{@const Icon = link.icon}
			<a href={link.href} aria-current={link.active ? 'page' : undefined} class={rowClass(link.active)}>
				<Icon class="size-5 shrink-0" aria-hidden="true" />
				<span class="flex-1">{link.label}</span>
				<ChevronRight class="size-4 text-zinc-400" aria-hidden="true" />
			</a>
			{#if link.href === CONTENT_ROOT && tree.length > 0}
				<ul class="ml-8 mb-1 flex flex-col border-l border-zinc-500/20 pl-2" aria-label="Livelli didattici">
					{#each tree as level (level.id)}
						{@const href = nodePath([level])}
						<li>
							<a
								{href}
								aria-current={pathname.startsWith(href) ? 'page' : undefined}
								class="flex min-h-[44px] items-center rounded-lg px-3 text-sm font-medium {pathname.startsWith(href)
									? 'text-crimson-700 dark:text-crimson-300'
									: 'text-zinc-600 hover:bg-zinc-100 dark:text-zinc-300 dark:hover:bg-zinc-800'}"
							>
								{level.title}
							</a>
						</li>
					{/each}
				</ul>
			{/if}
		{/each}
	</nav>

	<div class="my-3 border-t border-zinc-500/20"></div>

	<div class="flex min-h-[48px] items-center justify-between gap-3 px-3">
		<span class="text-base font-medium text-zinc-800 dark:text-zinc-100">Tema chiaro o scuro</span>
		<ThemeToggle />
	</div>

	<div class="my-3 border-t border-zinc-500/20"></div>

	{#if authState.user}
		<div class="flex flex-col gap-2 px-1">
			<a href={accountUrl} class={rowClass(pathname.startsWith(accountUrl))}>
				<UserRound class="size-5 shrink-0" aria-hidden="true" />
				<span class="flex-1">{isStaff(authState.user) ? 'Dashboard' : 'Il tuo account'}</span>
				<ChevronRight class="size-4 text-zinc-400" aria-hidden="true" />
			</a>
			{#if !isStaff(authState.user)}
				<a href="/richieste" class={rowClass(pathname.startsWith('/richieste'))}>
					<Mail class="size-5 shrink-0" aria-hidden="true" />
					<span class="flex-1">Le tue richieste ai tutor</span>
					<ChevronRight class="size-4 text-zinc-400" aria-hidden="true" />
				</a>
			{/if}
			<div class="px-2 pt-1 [&>button]:w-full [&>button]:min-h-[48px]">
				<LogoutButton />
			</div>
		</div>
	{:else}
		<div class="grid grid-cols-2 gap-2 px-1">
			<button
				type="button"
				onclick={() => login(false)}
				class="flex min-h-[48px] items-center justify-center gap-2 rounded-xl border border-zinc-500/25 bg-zinc-100 dark:bg-zinc-800 text-base font-semibold text-zinc-800 dark:text-zinc-100 active:bg-zinc-200 dark:active:bg-zinc-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500"
			>
				<LogIn class="size-5" aria-hidden="true" />
				Accedi
			</button>
			<button
				type="button"
				onclick={() => login(true)}
				class="flex min-h-[48px] items-center justify-center gap-2 rounded-xl bg-crimson-600 text-base font-semibold text-white active:bg-crimson-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-zinc-900"
			>
				<UserPlus class="size-5" aria-hidden="true" />
				Registrati
			</button>
		</div>
	{/if}
</Sheet>

// src/components/shell/MobileMenu.tsx
'use client';

import { useEffect, useRef } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Backpack, ChevronRight, CircleHelp, CreditCard, House, LibraryBig, LogIn, Mail, UserPlus, UserRound, UsersRound } from 'lucide-react';
import { CONTENT_ROOT, TUTORING_ROOT, ZAINO_ROOT } from '@/lib/config/site';
import { nodePath } from '@/lib/seo/slug';
import { useAuth } from '@/lib/state/auth';
import { isStaff } from '@/lib/auth/entitlements';
import { cn } from '@/lib/utils/cn';
import { Sheet } from '@/components/ui/Sheet';
import { Button } from '@/components/ui/Button';
import { useContentTree } from './ContentTreeContext';
import { ThemeToggle } from './ThemeToggle';
import { LogoutButton, accountUrl } from './AuthButtons';

const row = (active: boolean) => cn('flex min-h-[48px] items-center gap-3 rounded-xl px-3 text-base font-medium transition-colors focus-ring', active ? 'bg-accent-soft text-accent-soft-fg' : 'text-fg hover:bg-surface-3 active:bg-surface-3');

/** The phone menu: every section of the site, the theme and the account, in one sheet. */
export function MobileMenu({ open, onClose }: { open: boolean; onClose: () => void }) {
	const pathname = usePathname();
	const tree = useContentTree();
	const { user, openModal } = useAuth();

	// A navigation closes the sheet; nothing else does from here.
	const shownPath = useRef(pathname);
	useEffect(() => {
		if (shownPath.current === pathname) return;
		shownPath.current = pathname;
		onClose();
	}, [pathname, onClose]);

	const links = [
		{ href: '/', label: 'Home', icon: House, active: pathname === '/' },
		{ href: CONTENT_ROOT, label: 'Materiale didattico', icon: LibraryBig, active: pathname.startsWith(CONTENT_ROOT) },
		{ href: ZAINO_ROOT, label: 'Il tuo zaino', icon: Backpack, active: pathname.startsWith(ZAINO_ROOT) },
		{ href: TUTORING_ROOT, label: 'Ripetizioni', icon: UsersRound, active: pathname.startsWith(TUTORING_ROOT) },
		{ href: '/pricing', label: 'Prezzi e abbonamenti', icon: CreditCard, active: pathname.startsWith('/pricing') },
		{ href: '/faq', label: 'Domande frequenti', icon: CircleHelp, active: pathname === '/faq' },
		{ href: '/contacts', label: 'Contatti', icon: Mail, active: pathname === '/contacts' }
	];
	const login = (register: boolean) => {
		onClose();
		openModal({ register });
	};

	return (
		<Sheet open={open} onClose={onClose} title="Menu" bodyClass="px-3 pb-3">
			<nav aria-label="Menu" className="flex flex-col gap-0.5">
				{links.map(({ href, label, icon: Icon, active }) => (
					<div key={href}>
						<Link href={href} aria-current={active ? 'page' : undefined} className={row(active)}>
							<Icon className="size-5 shrink-0" aria-hidden="true" />
							<span className="flex-1">{label}</span>
							<ChevronRight className="size-4 text-fg-faint" aria-hidden="true" />
						</Link>
						{href === CONTENT_ROOT && tree.length > 0 && (
							<ul className="mb-1 ml-8 flex flex-col border-l border-edge pl-2" aria-label="Livelli didattici">
								{tree.map((level) => {
									const levelHref = nodePath([level]);
									const active = pathname.startsWith(levelHref);
									return (
										<li key={level.id}>
											<Link href={levelHref} aria-current={active ? 'page' : undefined} className={cn('flex min-h-[44px] items-center rounded-lg px-3 text-sm font-medium', active ? 'text-accent-soft-fg' : 'text-fg-muted hover:bg-surface-3')}>
												{level.title}
											</Link>
										</li>
									);
								})}
							</ul>
						)}
					</div>
				))}
			</nav>
			<hr className="my-3 border-edge" />
			<div className="flex min-h-[48px] items-center justify-between gap-3 px-3">
				<span className="text-base font-medium text-fg">Tema chiaro o scuro</span>
				<ThemeToggle />
			</div>
			<hr className="my-3 border-edge" />
			{user ? (
				<div className="flex flex-col gap-2 px-1">
					<Link href={accountUrl(user)} className={row(pathname.startsWith(accountUrl(user)))}>
						<UserRound className="size-5 shrink-0" aria-hidden="true" />
						<span className="flex-1">{isStaff(user) ? 'Dashboard' : 'Il tuo account'}</span>
						<ChevronRight className="size-4 text-fg-faint" aria-hidden="true" />
					</Link>
					{!isStaff(user) && (
						<Link href="/richieste" className={row(pathname.startsWith('/richieste'))}>
							<Mail className="size-5 shrink-0" aria-hidden="true" />
							<span className="flex-1">Le tue richieste ai tutor</span>
							<ChevronRight className="size-4 text-fg-faint" aria-hidden="true" />
						</Link>
					)}
					<div className="px-2 pt-1">
						<LogoutButton className="min-h-[48px] w-full" />
					</div>
				</div>
			) : (
				<div className="grid grid-cols-2 gap-2 px-1">
					<Button variant="secondary" size="lg" onClick={() => login(false)}>
						<LogIn className="size-5" aria-hidden="true" />
						Accedi
					</Button>
					<Button size="lg" onClick={() => login(true)}>
						<UserPlus className="size-5" aria-hidden="true" />
						Registrati
					</Button>
				</div>
			)}
		</Sheet>
	);
}
