// src/lib/components/shared/landing/SubjectMegaMenu.svelte
<script lang="ts">
	import { fly, fade } from 'svelte/transition';
	import { goto } from '$app/navigation';
	import { contentTree, EducationalLevelMap } from '$lib/data/content-tree';
	import { Plus } from 'lucide-svelte';

	let {
		isOpen = false,
		level,
		columnsCount = 3,
		topicsPerChapter = 3
	} = $props();


	let subjects = $derived(contentTree.find(l => l.id === level.id)?.subjects || []);
	
	let selectedSubject = $state<string | null>(null);
	
	// Set default selected subject when menu opens
	$effect(() => {
		if (isOpen && subjects.length > 0 && !selectedSubject) {
			selectedSubject = subjects[0].id;
		}
		if (!isOpen) {
			selectedSubject = null;
		}
	});
	
	function handleChapterClick(subject_id: string, chapter_id: string) {
		goto(`/${level.id}/${subject_id}/${chapter_id}`);
	}

	function handleTopicClick(subject_id: string, chapter_id: string, topic_id: string) {
		goto(`/${level.id}/${subject_id}/${chapter_id}/${topic_id}`);
	}
	
	function handleLevelHover(subjectId: string) {
		selectedSubject = subjectId;
	}
	
	let currentSubjectData = $derived(
		subjects.find(s => s.id === selectedSubject) || subjects[0]
	);
</script>

<div
	class="w-full max-h-[80vh] overflow-hidden bg-white dark:bg-zinc-900 border-b border-t border-zinc-200 dark:border-zinc-700 shadow-lg pointer-events-auto"
	role="menu"
	tabindex="-1"
	in:fly={{ y: -200, duration: 250, opacity: 0 }}
	out:fade={{ duration: 150 }}
>
	<!-- Header -->
	<div class="px-8 py-5 border-b border-zinc-200 dark:border-zinc-700 bg-zinc-50 dark:bg-zinc-800/50">
		<div class="mx-auto flex items-center gap-3">
			<level.icon class="size-6 text-rose-500 dark:text-rose-400" />
			<h3 class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">
				{EducationalLevelMap[level.id]}
			</h3>
		</div>
	</div>
	
	<!-- Main Content -->
	<div class="mx-auto flex min-h-[400px] overflow-hidden">
		<!-- Left Sidebar - Educational Levels -->
		<div class="w-1/6 border-r border-zinc-200 dark:border-zinc-700 bg-zinc-50/50 dark:bg-zinc-800/30">
			{#each subjects as subjectData}
				<button
					onmouseenter={() => handleLevelHover(subjectData.id)}
					class="
						w-full flex items-center gap-2 text-left px-6 py-4 text-base font-medium transition-all duration-200
						text-zinc-700 dark:text-zinc-300 hover:text-rose-500 dark:hover:text-rose-400
						hover:bg-white dark:hover:bg-zinc-800 
							border-l-3
						{
							selectedSubject === subjectData.id ? 
								'bg-white dark:bg-zinc-800 border-rose-500 dark:border-rose-400 text-rose-500 dark:text-rose-400' : 
								'border-transparent'
						}
					"
				>
					<subjectData.icon class="size-4" />
					<span class="font-medium">{subjectData.name}</span>
				</button>
			{/each}
		</div>
		
		<!-- Right Content Area - chapters columns -->
		<div class="flex-1 p-8 overflow-y-auto h-full">
			{#if currentSubjectData}
				<div class="gap-6 h-full" style="column-count: {columnsCount}; column-gap: 1.5rem; width: 100%;">
					{#each currentSubjectData.chapters as chapter, index}
						<div class="flex flex-col gap-4 mb-8" style="break-inside: avoid;">
							<button
								onclick={() => handleChapterClick(currentSubjectData.id, chapter.id)}
								class="w-full text-left px-0 text-zinc-900 dark:text-zinc-100 transition-all duration-200 relative group"
							>
								<span class="font-semibold line-clamp-1">
									{index + 1}. {chapter.name}
								</span>
								<span class="absolute -bottom-2 left-1/2 -translate-x-1/2 h-0.5 bg-rose-500 rounded-full transition-all duration-200 opacity-0 w-0 group-hover:opacity-100 group-hover:w-full"></span>
							</button>

							<div class="flex flex-col gap-1.5">
								{#each chapter.topics.slice(0, topicsPerChapter) as topic}
									<button
										onclick={() => handleTopicClick(currentSubjectData.id, chapter.id, topic.id)}
										class="w-full text-left px-3 ps-0 hover:ps-3 py-1.5 rounded-lg text-sm  hover:bg-zinc-100 dark:hover:bg-zinc-800  transition-all duration-200 group relative"
									>
										<span class="text-zinc-600 dark:text-zinc-400 group-hover:text-rose-500 dark:group-hover:text-rose-400 line-clamp-1">
											{topic.name}
										</span>
									</button>
								{/each}

								{#if chapter.topics.length == topicsPerChapter + 1}
									{@const topic = chapter.topics[topicsPerChapter]}
									<button
										onclick={() => handleTopicClick(currentSubjectData.id, chapter.id, topic.id)}
										class="w-full text-left px-3 ps-0 hover:ps-3 py-1.5 rounded-lg text-sm  hover:bg-zinc-100 dark:hover:bg-zinc-800  transition-all duration-200 group relative"
									>
										<span class="text-zinc-600 dark:text-zinc-400 group-hover:text-rose-500 dark:group-hover:text-rose-400 line-clamp-1">
											{topic.name}
										</span>
									</button>
								{:else if chapter.topics.length > topicsPerChapter + 1}
									<button
										onclick={() => handleChapterClick(currentSubjectData.id, chapter.id)}
										class="w-full flex items-center text-left py-1.5 rounded-lg text-xs text-zinc-500 dark:text-zinc-500 hover:text-rose-500 dark:hover:text-rose-400 transition-all duration-200"
									>
										<Plus class="size-3" />
										<span>{chapter.topics.length - topicsPerChapter} argomenti</span>
									</button>
								{/if}
							</div>
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>

// src/components/shell/SubjectMegaMenu.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Plus } from 'lucide-react';
import type { ContentNode } from '@/lib/utils/tree';
import { nodePath, plainTitle } from '@/lib/seo/slug';
import { cn } from '@/lib/utils/cn';

/** The level's subjects down the left, the hovered subject's chapters and first lessons across the right. Opened from the keyboard, the first subject takes focus. */
export function SubjectMegaMenu({ level, onClose, autoFocus = false, columns = 5, topicsPerChapter = 4 }: { level: ContentNode; onClose: () => void; autoFocus?: boolean; columns?: number; topicsPerChapter?: number }) {
	const [subject, setSubject] = useState<ContentNode | null>(level.children[0] ?? null);
	const [shownLevel, setShownLevel] = useState(level);
	const root = useRef<HTMLElement>(null);
	if (level !== shownLevel) {
		setShownLevel(level);
		setSubject(level.children[0] ?? null);
	}
	const chapters = subject?.children ?? [];
	useEffect(() => {
		if (autoFocus) root.current?.querySelector<HTMLElement>('a[href]')?.focus();
	}, [autoFocus, level]);

	return (
		<nav ref={root} className="max-h-[80vh] w-full animate-drop-in overflow-hidden border-b border-t border-edge bg-surface shadow-lg" aria-label={`Materie di ${level.title}`}>
			<div className="border-b border-edge bg-surface-2 px-8 py-5">
				<p className="text-xl font-semibold text-fg">{level.title}</p>
			</div>
			<div className="flex min-h-[400px] overflow-hidden">
				<div className="w-1/6 border-r border-edge bg-surface-2/50">
					{level.children.map((s) => (
						<Link
							key={s.id}
							href={nodePath([level, s])}
							onClick={onClose}
							onMouseEnter={() => setSubject(s)}
							onFocus={() => setSubject(s)}
							className={cn('flex w-full items-center gap-2 border-l-3 px-6 py-4 text-left text-base font-medium transition-all hover:bg-surface hover:text-accent-fg', subject?.id === s.id ? 'border-accent bg-surface text-accent-fg' : 'border-transparent text-fg-muted')}
						>
							{s.title}
						</Link>
					))}
				</div>
				<div className="h-full flex-1 overflow-y-auto p-8">
					{subject && (
						<div style={{ columnCount: columns, columnGap: '1.5rem' }}>
							{chapters.map((chapter, index) => {
								const topics = chapter.children;
								const shown = topics.length === topicsPerChapter + 1 ? topics : topics.slice(0, topicsPerChapter);
								return (
									<div key={chapter.id} className="mb-8 flex flex-col gap-4" style={{ breakInside: 'avoid' }}>
										<Link href={nodePath([level, subject, chapter])} onClick={onClose} className="group relative flex items-center gap-2 text-fg">
											<span className="line-clamp-1 font-semibold">{index + 1}. {plainTitle(chapter.title)}</span>
											<span className="absolute -bottom-2 left-1/2 h-0.5 w-0 -translate-x-1/2 rounded-full bg-accent opacity-0 transition-all group-hover:w-full group-hover:opacity-100" aria-hidden="true" />
										</Link>
										<div className="flex flex-col gap-1.5">
											{shown.map((topic) => (
												<Link key={topic.id} href={nodePath([level, subject, chapter, topic])} onClick={onClose} className="group rounded-lg py-1.5 ps-0 pe-3 text-sm transition-all hover:bg-surface-3 hover:ps-3">
													<span className="line-clamp-1 text-fg-muted group-hover:text-accent-fg">{plainTitle(topic.title)}</span>
												</Link>
											))}
											{topics.length > topicsPerChapter + 1 && (
												<Link href={nodePath([level, subject, chapter])} onClick={onClose} className="flex items-center py-1.5 text-xs text-fg-subtle hover:text-accent-fg">
													<Plus className="size-3" aria-hidden="true" />
													<span>{topics.length - topicsPerChapter} lezioni</span>
												</Link>
											)}
										</div>
									</div>
								);
							})}
						</div>
					)}
				</div>
			</div>
		</nav>
	);
}
