// src/lib/components/landing/HeroSection.svelte
<script lang="ts">
	import { GraduationCap, BookOpen } from 'lucide-svelte';
	import landing from '$lib/assets/landing.png?enhanced';

	import AnimatedCounter from '$lib/components/ui/AnimatedCounter.svelte';

	interface Props {
		heroSection: HTMLElement | null;
		stats: {
			value: number;
			label: string;
			icon: typeof GraduationCap;
		}[];
	}

    let {
        heroSection = $bindable(null),
        stats,
    }: Props = $props();

	// The screenshot is the largest element of the desktop hero: preload the
	// AVIF candidates so the browser starts fetching before the CSS lands.
	const imageSizes = '(min-width: 1024px) 50vw, 1px';
</script>

<svelte:head>
	{#if landing.sources.avif}
		<link
			rel="preload"
			as="image"
			type="image/avif"
			imagesrcset={landing.sources.avif}
			imagesizes={imageSizes}
			media="(min-width: 1024px)"
		/>
	{/if}
</svelte:head>

<section
    bind:this={heroSection}
    class="relative min-h-screen flex items-center justify-center pb-24 px-6 lg:px-8 overflow-hidden"
>
	<div class="relative max-w-7xl mx-auto w-full z-10">
		<div class="grid lg:grid-cols-2 gap-2 items-center">
			<div class="text-center lg:text-left space-y-8">
				<div class="space-y-6">
					<h1 class="text-4xl sm:text-5xl lg:text-[2.25rem] font-bold text-gray-900 dark:text-slate-50 leading-[1.2] tracking-tight">
						Studia in autonomia con
						<span class="block mt-2 text-crimson-500 dark:text-crimson-400">
							materiale chiaro e completo
						</span>
					</h1>

					<p class="text-base sm:text-lg text-gray-600 dark:text-gray-400 leading-[1.6] max-w-2xl mx-auto lg:mx-0">
						Teoria, formulari ed esercizi svolti per medie e superiori. Con Premium accedi a lezioni individuali e supporto personalizzato.
					</p>
				</div>

				<div class="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
					<a
						href="/pricing"
						class="group inline-flex items-center justify-center gap-2 bg-crimson-600 hover:bg-crimson-700 dark:bg-crimson-600 dark:hover:bg-crimson-700 text-white px-8 py-4 rounded-xl font-medium text-base shadow-sm hover:shadow-md transition-all duration-300 ease-in-out hover:scale-[1.02] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500 focus-visible:ring-offset-2"
					>
						<GraduationCap class="w-5 h-5 transition-transform duration-300 ease-in-out group-hover:rotate-12" aria-hidden="true" />
						<span>Scopri i piani</span>
					</a>

					<a
						href="/materiale"
						class="group inline-flex items-center justify-center gap-2 bg-white dark:bg-[#12161B] border border-zinc-500/25 hover:border-zinc-500/50 text-gray-900 dark:text-slate-50 px-8 py-4 rounded-xl font-medium text-base shadow-sm hover:shadow-md transition-all duration-300 ease-in-out hover:scale-[1.02] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500 focus-visible:ring-offset-2"
					>
						<BookOpen class="w-5 h-5" aria-hidden="true" />
						<span>Esplora materiale</span>
					</a>
				</div>

				<div class="flex items-center justify-center lg:justify-start gap-8 pt-8">
					{#each stats as stat}
						{@const StatIcon = stat.icon}
						<div class="text-center lg:text-left">
							<div class="flex items-center gap-3">
								<StatIcon class="size-6 text-crimson-500 dark:text-crimson-400" aria-hidden="true" />
								<div class="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-slate-50">
									<AnimatedCounter target={stat.value} duration={2000} />
								</div>
							</div>
							<div class="text-sm text-gray-600 dark:text-gray-400 mt-1">
								{stat.label}
							</div>
						</div>
					{/each}
				</div>
			</div>

			<div class="hidden lg:block">
				<div class="relative">
					<div class="relative overflow-hidden">
						<enhanced:img
							src={landing}
							alt="Una lezione di Sapiens aperta nel browser, con indice a sinistra e teoria al centro"
							sizes={imageSizes}
							fetchpriority="high"
							decoding="async"
							class="w-full h-auto object-cover"
						/>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

// src/components/landing/HeroSection.tsx
import Image from 'next/image';
import { BookOpen, GraduationCap, Layers, LibraryBig } from 'lucide-react';
import { LinkButton } from '@/components/ui/Button';
import { AnimatedCounter } from './AnimatedCounter';
import landing from '@/assets/landing.png';

export interface HeroCounts {
	subject: number;
	chapter: number;
	published: number;
}

/** The landing hero: the promise, two calls to action, live content figures and the desktop screenshot. */
export function HeroSection({ counts }: { counts: HeroCounts }) {
	// Content figures only, straight from the database: the library is what exists today.
	const stats = [
		{ value: counts.subject, label: 'Materie', icon: LibraryBig },
		{ value: counts.chapter, label: 'Capitoli', icon: Layers },
		{ value: counts.published, label: 'Lezioni pubblicate', icon: BookOpen }
	];
	return (
		<section className="relative flex items-center justify-center overflow-hidden px-5 pb-16 pt-10 sm:px-6 lg:min-h-screen lg:px-8 lg:pb-24 lg:pt-0">
			<div className="relative z-10 mx-auto w-full max-w-7xl">
				<div className="grid items-center gap-2 lg:grid-cols-2">
					<div className="space-y-8 text-center lg:text-left">
						<div className="space-y-6">
							<h1 className="text-4xl font-bold leading-[1.2] tracking-tight text-fg-strong sm:text-5xl lg:text-[2.25rem]">
								Studia in autonomia con
								<span className="mt-2 block text-accent-fg">materiale chiaro e completo</span>
							</h1>
							<p className="mx-auto max-w-2xl text-base leading-[1.6] text-fg-muted sm:text-lg lg:mx-0">
								Teoria, formulari ed esercizi svolti per medie e superiori. Con Premium accedi a lezioni individuali e supporto personalizzato.
							</p>
						</div>
						<div className="flex flex-col justify-center gap-4 sm:flex-row lg:justify-start">
							<LinkButton href="/pricing" size="lg" className="group px-8 py-4 transition-transform hover:scale-[1.02]">
								<GraduationCap className="size-5 transition-transform duration-300 group-hover:rotate-12" aria-hidden="true" />
								<span>Scopri i piani</span>
							</LinkButton>
							<LinkButton href="/materiale" variant="secondary" size="lg" className="bg-surface px-8 py-4 transition-transform hover:scale-[1.02]">
								<BookOpen className="size-5" aria-hidden="true" />
								<span>Esplora materiale</span>
							</LinkButton>
						</div>
						<div className="flex flex-wrap items-center justify-center gap-x-8 gap-y-4 pt-8 lg:justify-start">
							{stats.map(({ value, label, icon: Icon }) => (
								<div key={label} className="text-center lg:text-left">
									<div className="flex items-center gap-3">
										<Icon className="size-6 text-accent-fg" aria-hidden="true" />
										<div className="text-2xl font-bold text-fg-strong sm:text-3xl">
											<AnimatedCounter target={value} />
										</div>
									</div>
									<div className="mt-1 text-sm text-fg-muted">{label}</div>
								</div>
							))}
						</div>
					</div>
					<div className="hidden lg:block">
						{/* The screenshot is the largest element of the desktop hero: fetched first, as AVIF where supported. */}
						<Image src={landing} alt="Una lezione di Sapiens aperta nel browser, con indice a sinistra e teoria al centro" sizes="(min-width: 1024px) 50vw, 1px" priority className="h-auto w-full object-cover" />
					</div>
				</div>
			</div>
		</section>
	);
}
