// src/lib/components/shared/landing/HeroSection.svelte
<script lang="ts">
	import { themeStore } from '$lib/components/shared/ui/theme/theme';
	import { GraduationCap, BookOpen } from 'lucide-svelte';

	interface Props {
		heroSection: HTMLElement | null;
		stats: {
			value: string;
			label: string;
			icon: typeof GraduationCap;
		}[];
	}

    let { 
        heroSection = $bindable(null),
        stats,
    }: Props = $props();
</script>

<section
    bind:this={heroSection}
    class="relative min-h-screen flex items-center justify-center pb-24 px-6 lg:px-8 overflow-hidden"
>
	<div aria-hidden="true" class="absolute inset-0 pointer-events-none opacity-40 dark:opacity-20">
		<div class="absolute top-0 right-0 w-[500px] h-[500px] bg-rose-500/10 dark:bg-rose-400/10 rounded-full blur-[120px]"></div>
		<div class="absolute bottom-0 left-0 w-[400px] h-[400px] bg-blue-500/10 dark:bg-blue-400/10 rounded-full blur-[120px]"></div>
	</div>

	<div class="relative max-w-7xl mx-auto w-full z-10">
		<div class="grid lg:grid-cols-2 gap-16 items-center">
			<div class="text-center lg:text-left space-y-8">
				<div class="space-y-6">
					<h1 class="text-4xl sm:text-5xl lg:text-[2.25rem] font-bold text-gray-900 dark:text-slate-50 leading-[1.2] tracking-tight">
						Studia in autonomia con
						<span class="block mt-2 text-rose-500 dark:text-rose-400">
							materiale chiaro e completo
						</span>
					</h1>

					<p class="text-base sm:text-lg text-gray-600 dark:text-gray-400 leading-[1.6] max-w-2xl mx-auto lg:mx-0">
						Teoria, formulari ed esercizi svolti per medie e superiori. Con Premium accedi a lezioni individuali e supporto personalizzato.
					</p>
				</div>

				<div class="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
					<a
						href="/pricing"
						class="group inline-flex items-center justify-center gap-2 bg-rose-500 hover:bg-rose-600 dark:bg-rose-400 dark:hover:bg-rose-500 text-white px-8 py-4 rounded-xl font-medium text-base shadow-sm hover:shadow-md transition-all duration-300 ease-in-out hover:scale-[1.02]"
					>
						<GraduationCap class="w-5 h-5 transition-transform duration-300 ease-in-out group-hover:rotate-12" />
						<span>Scopri i piani</span>
					</a>

					<a
						href="/search"
						class="group inline-flex items-center justify-center gap-2 bg-white dark:bg-[#12161B] border border-gray-300 dark:border-gray-800 hover:border-gray-400 dark:hover:border-gray-700 text-gray-900 dark:text-slate-50 px-8 py-4 rounded-xl font-medium text-base shadow-sm hover:shadow-md transition-all duration-300 ease-in-out hover:scale-[1.02]"
					>
						<BookOpen class="w-5 h-5" />
						<span>Esplora materiale</span>
					</a>
				</div>

				<div class="flex items-center justify-center lg:justify-start gap-8 pt-8">
					{#each stats as stat}
						{@const StatIcon = stat.icon}
						<div class="text-center lg:text-left">
							<div class="flex items-center gap-3">
								<StatIcon class="size-6 text-rose-500 dark:text-rose-400" />
								<div class="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-slate-50">
									{stat.value}
								</div>
							</div>
							<div class="text-sm text-gray-600 dark:text-gray-400 mt-1">
								{stat.label}
							</div>
						</div>
					{/each}
				</div>
			</div>

			<div class="hidden lg:block">
				<div class="relative">
					<div class="relative overflow-hidden">
						<img
							src="/landing-page.png"
							alt="Anteprima della piattaforma educativa Sapiens"
							loading="lazy"
							decoding="async"
							class="w-full h-auto object-cover"
							style="filter: { $themeStore === 'dark' ? 'invert(1)' : 'none' }"
						/>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Scroll indicator -->
	<!-- <a 
		href="#about" 
		aria-label="Scopri di più"
		class="hidden sm:flex items-center justify-center absolute left-1/2 -translate-x-1/2 bottom-8 w-10 h-10 rounded-full border border-gray-300 dark:border-gray-800 bg-white/80 dark:bg-[#12161B]/80 backdrop-blur-sm text-gray-600 dark:text-gray-400 shadow-sm hover:shadow-md hover:border-rose-500 dark:hover:border-rose-400 transition-all duration-300 ease-in-out animate-bounce"
	>
		<ChevronDown class="w-5 h-5" />
	</a> -->
</section>

// src/components/landing/HeroSection.tsx
import Image from 'next/image';
import { BookOpen, GraduationCap, Layers, LibraryBig } from 'lucide-react';
import { LinkButton } from '@/components/ui/Button';
import { AnimatedCounter } from './AnimatedCounter';
import landing from '@/assets/landing.png';

export interface HeroCounts {
	subject: number;
	chapter: number;
	published: number;
}

/** The landing hero: the promise, two calls to action, live content figures and the desktop screenshot. */
export function HeroSection({ counts }: { counts: HeroCounts }) {
	// Content figures only, straight from the database: the library is what exists today.
	const stats = [
		{ value: counts.subject, label: 'Materie', icon: LibraryBig },
		{ value: counts.chapter, label: 'Capitoli', icon: Layers },
		{ value: counts.published, label: 'Lezioni pubblicate', icon: BookOpen }
	];
	return (
		<section className="relative flex items-center justify-center overflow-hidden px-5 pb-16 pt-10 sm:px-6 lg:min-h-screen lg:px-8 lg:pb-24 lg:pt-0">
			<div className="relative z-10 mx-auto w-full max-w-7xl">
				<div className="grid items-center gap-2 lg:grid-cols-2">
					<div className="space-y-8 text-center lg:text-left">
						<div className="space-y-6">
							<h1 className="text-4xl font-bold leading-[1.2] tracking-tight text-fg-strong sm:text-5xl lg:text-[2.25rem]">
								Studia in autonomia con
								<span className="mt-2 block text-accent-fg">materiale chiaro e completo</span>
							</h1>
							<p className="mx-auto max-w-2xl text-base leading-[1.6] text-fg-muted sm:text-lg lg:mx-0">
								Teoria, formulari ed esercizi svolti per medie e superiori. Con Premium accedi a lezioni individuali e supporto personalizzato.
							</p>
						</div>
						<div className="flex flex-col justify-center gap-4 sm:flex-row lg:justify-start">
							<LinkButton href="/pricing" size="lg" className="group px-8 py-4 transition-transform hover:scale-[1.02]">
								<GraduationCap className="size-5 transition-transform duration-300 group-hover:rotate-12" aria-hidden="true" />
								<span>Scopri i piani</span>
							</LinkButton>
							<LinkButton href="/materiale" variant="secondary" size="lg" className="bg-surface px-8 py-4 transition-transform hover:scale-[1.02]">
								<BookOpen className="size-5" aria-hidden="true" />
								<span>Esplora materiale</span>
							</LinkButton>
						</div>
						<div className="flex flex-wrap items-center justify-center gap-x-8 gap-y-4 pt-8 lg:justify-start">
							{stats.map(({ value, label, icon: Icon }) => (
								<div key={label} className="text-center lg:text-left">
									<div className="flex items-center gap-3">
										<Icon className="size-6 text-accent-fg" aria-hidden="true" />
										<div className="text-2xl font-bold text-fg-strong sm:text-3xl">
											<AnimatedCounter target={value} />
										</div>
									</div>
									<div className="mt-1 text-sm text-fg-muted">{label}</div>
								</div>
							))}
						</div>
					</div>
					<div className="hidden lg:block">
						{/* The screenshot is the largest element of the desktop hero: fetched first, as AVIF where supported. */}
						<Image src={landing} alt="Una lezione di Sapiens aperta nel browser, con indice a sinistra e teoria al centro" sizes="(min-width: 1024px) 50vw, 1px" priority className="h-auto w-full object-cover" />
					</div>
				</div>
			</div>
		</section>
	);
}
