// src/lib/components/seo/JsonLd.svelte
<script lang="ts">
	import type { JsonLd } from '$lib/seo/jsonld';

	let { data }: { data: JsonLd | JsonLd[] } = $props();

	// A closing script tag inside a JSON string would end the block early, so "<" is escaped.
	let blocks = $derived(
		(Array.isArray(data) ? data : [data]).map(
			(d) => `<script type="application/ld+json">${JSON.stringify(d).replace(/</g, '\\u003c')}<\/script>`
		)
	);
</script>

<svelte:head>
	{#each blocks as block}
		{@html block}
	{/each}
</svelte:head>

// src/components/seo/JsonLd.tsx
import type { JsonLd as JsonLdData } from '@/lib/seo/jsonld';

/** Structured data, serialised with `<` escaped so the script cannot be closed early. */
export function JsonLd({ data }: { data: JsonLdData | JsonLdData[] | undefined }) {
	if (!data) return null;
	const items = Array.isArray(data) ? data : [data];
	return items.map((item, i) => (
		<script key={i} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(item).replace(/</g, '\\u003c') }} />
	));
}
