// src/lib/components/subscription/Paywall.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { Lock, Check, ArrowLeft, Loader2 } from 'lucide-svelte';
	import { Features, FeaturesDetails, formatPrice, TRIAL_DAYS } from '$lib/stripe/config';
	import { requiredPlanFor, featuresUnlockedBy, trialAvailable } from '$lib/auth/entitlements';
	import { authState } from '$lib/state/auth.svelte';
	import { requestCheckout } from '$lib/subscription/checkout';

	/**
	 * Shown in place of a Premium feature the visitor cannot use. States the
	 * plan that includes it, what else that plan unlocks, the price and the
	 * trial, and starts the checkout in one click (login first, if needed).
	 * No timers, no fake scarcity: the content behind is what sells it.
	 */

	interface Props {
		feature: Features;
		/** Page to come back to once the plan is active. */
		returnTo: string;
		/** Where the "back" link goes (the lesson's theory, usually). */
		backUrl?: string;
		backLabel?: string;
		/** A one-line, true description of what the feature does. */
		benefit: string;
		/** Rendered, blurred and inert, behind the card. */
		preview?: Snippet;
		/** Narrow version for sidebars. */
		compact?: boolean;
	}

	let { feature, returnTo, backUrl, backLabel = 'Torna alla teoria', benefit, preview, compact = false }: Props = $props();

	const COPY: Record<Features, { subject: string; title: (plan: string) => string }> = {
		[Features.EXERCISES]: { subject: 'esercizi', title: (p) => `Gli esercizi interattivi sono inclusi nel piano ${p}` },
		[Features.FLASHCARDS]: { subject: 'flashcard', title: (p) => `Le flashcard sono incluse nel piano ${p}` },
		[Features.AI_CHAT]: { subject: 'Sapiens AI', title: (p) => `Sapiens AI è incluso nel piano ${p}` },
		[Features.TUTORING]: { subject: 'ripetizioni', title: (p) => `Le ripetizioni 1 a 1 sono incluse nel piano ${p}` },
		[Features.REMOVE_ADS]: { subject: 'navigazione senza pubblicità', title: (p) => `Inclusa nel piano ${p}` },
		[Features.THEORY]: { subject: 'teoria', title: (p) => `Inclusa nel piano ${p}` }
	};

	let plan = $derived(requiredPlanFor(feature));
	let shortName = $derived(plan.name.replace(/^Piano\s+/i, ''));
	let unlocked = $derived(featuresUnlockedBy(plan));
	let withTrial = $derived(!authState.user || trialAvailable(authState.user));

	let busy = $state(false);
	let error = $state<string | null>(null);

	async function upgrade() {
		busy = true;
		error = null;
		try {
			await requestCheckout({ planId: plan.id, returnTo });
		} catch (err) {
			error = err instanceof Error ? err.message : 'Qualcosa è andato storto. Riprova.';
		} finally {
			busy = false;
		}
	}
</script>

<div class="relative {compact ? '' : 'h-full min-h-[60vh]'}" id="paywall">
	{#if preview}
		<div class="pointer-events-none select-none blur-sm opacity-50" aria-hidden="true" inert>
			{@render preview()}
		</div>
	{/if}

	<div class="{preview ? 'absolute inset-0' : ''} flex items-center justify-center {compact ? 'p-3' : 'p-6'}">
		<section
			class="w-full {compact ? 'max-w-sm p-5' : 'max-w-md p-8'} rounded-3xl bg-white dark:bg-zinc-900 border border-zinc-500/25 shadow-xl text-center"
			aria-labelledby="paywall-title"
		>
			<div class="mx-auto {compact ? 'size-11 mb-3' : 'size-16 mb-5'} rounded-full bg-crimson-50 dark:bg-crimson-900/20 text-crimson-600 dark:text-crimson-400 flex items-center justify-center">
				<Lock class={compact ? 'size-5' : 'size-7'} aria-hidden="true" />
			</div>

			<h2 id="paywall-title" class="{compact ? 'text-base' : 'text-2xl'} font-bold text-zinc-900 dark:text-zinc-50 tracking-tight leading-snug">
				{COPY[feature].title(shortName)}
			</h2>

			<p class="mt-2 {compact ? 'text-sm' : ''} text-zinc-600 dark:text-zinc-400 leading-relaxed">
				{benefit}
			</p>

			{#if unlocked.length > 1 && !compact}
				<ul class="mt-5 text-left text-sm text-zinc-700 dark:text-zinc-300 flex flex-col gap-2" aria-label="Incluso nel piano {shortName}">
					{#each unlocked as f (f)}
						<li class="flex items-center gap-2.5">
							<Check class="size-4 shrink-0 text-crimson-600 dark:text-crimson-400" aria-hidden="true" />
							<span>{FeaturesDetails[f].name}</span>
						</li>
					{/each}
				</ul>
			{/if}

			<p class="mt-5 text-sm text-zinc-600 dark:text-zinc-400">
				<span class="font-semibold text-zinc-900 dark:text-zinc-100">{formatPrice(plan.price, plan.currency)} al mese</span>
				{#if withTrial}
					· primi {TRIAL_DAYS} giorni gratis, senza carta
				{/if}
				· disdici quando vuoi
			</p>

			<button
				type="button"
				onclick={upgrade}
				disabled={busy}
				class="mt-5 w-full inline-flex items-center justify-center gap-2 rounded-xl bg-crimson-600 hover:bg-crimson-700 text-white font-semibold {compact ? 'py-2.5 text-sm' : 'py-3.5'} px-6 transition-colors disabled:opacity-60 disabled:cursor-wait focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-zinc-900"
			>
				{#if busy}
					<Loader2 class="size-4 animate-spin" aria-hidden="true" />
					<span>Un attimo…</span>
				{:else if withTrial}
					Prova {shortName} gratis per {TRIAL_DAYS} giorni
				{:else}
					Attiva il piano {shortName}
				{/if}
			</button>

			{#if error}
				<p class="mt-3 text-sm text-red-600 dark:text-red-400" role="alert">{error}</p>
			{/if}

			<div class="mt-4 flex flex-col items-center gap-2 text-sm">
				<a href="/pricing" class="text-zinc-600 dark:text-zinc-400 hover:text-crimson-600 dark:hover:text-crimson-400 underline underline-offset-2 rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500">
					Confronta tutti i piani
				</a>
				{#if authState.ready && !authState.user}
					<button
						type="button"
						onclick={() => authState.openModal()}
						class="text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500"
					>
						Hai già un abbonamento? Accedi
					</button>
				{/if}
			</div>

			{#if backUrl}
				<a
					href={backUrl}
					class="mt-5 inline-flex items-center gap-2 text-sm text-zinc-500 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500"
				>
					<ArrowLeft class="size-4" aria-hidden="true" />
					{backLabel}
				</a>
			{/if}
		</section>
	</div>
</div>

// src/components/subscription/Paywall.tsx
'use client';

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowLeft, Check, Loader2, Lock } from 'lucide-react';
import { Features, FeaturesDetails, TRIAL_DAYS, formatPrice } from '@/lib/stripe/config';
import { featuresUnlockedBy, requiredPlanFor, trialAvailable } from '@/lib/auth/entitlements';
import { useAuth } from '@/lib/state/auth';
import { requestCheckout } from '@/lib/subscription/checkout';
import { cn } from '@/lib/utils/cn';

const COPY: Record<Features, (plan: string) => string> = {
	[Features.EXERCISES]: (p) => `Gli esercizi interattivi sono inclusi nel piano ${p}`,
	[Features.FLASHCARDS]: (p) => `Le flashcard sono incluse nel piano ${p}`,
	[Features.NOTEBOOKS]: (p) => `Quaderni e note senza limiti sono inclusi nel piano ${p}`,
	[Features.AI_CHAT]: (p) => `Sapiens AI è incluso nel piano ${p}`,
	[Features.TUTORING]: (p) => `Le ripetizioni 1 a 1 sono incluse nel piano ${p}`,
	[Features.REMOVE_ADS]: (p) => `Inclusa nel piano ${p}`,
	[Features.THEORY]: (p) => `Inclusa nel piano ${p}`
};

interface Props {
	feature: Features;
	/** Page to come back to once the plan is active. */
	returnTo: string;
	/** Where the "back" link goes (the lesson's theory, usually). */
	backUrl?: string;
	/** A one-line, true description of what the feature does. */
	benefit: string;
	/** Rendered, blurred and inert, behind the card. */
	preview?: ReactNode;
	/** Narrow version for sidebars. */
	compact?: boolean;
}

/**
 * Shown in place of a Premium feature the visitor cannot use. States the
 * plan that includes it, what else that plan unlocks, the price and the
 * trial, and starts the checkout in one click (login first, if needed).
 * No timers, no fake scarcity: the content behind is what sells it.
 */
export function Paywall({ feature, returnTo, backUrl, benefit, preview, compact = false }: Props) {
	const { user, ready, openModal } = useAuth();
	const [busy, setBusy] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const plan = requiredPlanFor(feature);
	const name = plan.name.replace(/^Piano\s+/i, '');
	const unlocked = featuresUnlockedBy(plan);
	const withTrial = !user || trialAvailable(user);

	const upgrade = async () => {
		setBusy(true);
		setError(null);
		try {
			await requestCheckout({ planId: plan.id, returnTo });
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Qualcosa è andato storto. Riprova.');
		} finally {
			setBusy(false);
		}
	};

	return (
		<div className={cn('relative', !compact && 'h-full min-h-[60vh]')} id="paywall">
			{preview && (
				<div className="pointer-events-none select-none opacity-50 blur-sm" aria-hidden="true" inert>
					{preview}
				</div>
			)}
			<div className={cn('flex items-center justify-center', !!preview && 'absolute inset-0', compact ? 'p-3' : 'p-6')}>
				<section className={cn('w-full rounded-3xl border border-edge bg-surface text-center shadow-xl', compact ? 'max-w-sm p-5' : 'max-w-md p-8')} aria-labelledby="paywall-title">
					<div className={cn('mx-auto flex items-center justify-center rounded-full bg-accent-soft text-accent-fg', compact ? 'mb-3 size-11' : 'mb-5 size-16')}>
						<Lock className={compact ? 'size-5' : 'size-7'} aria-hidden="true" />
					</div>
					<h2 id="paywall-title" className={cn('font-bold leading-snug tracking-tight text-fg-strong', compact ? 'text-base' : 'text-2xl')}>
						{COPY[feature](name)}
					</h2>
					<p className={cn('mt-2 leading-relaxed text-fg-muted', compact && 'text-sm')}>{benefit}</p>
					{unlocked.length > 1 && !compact && (
						<ul className="mt-5 flex flex-col gap-2 text-left text-sm text-fg-muted" aria-label={`Incluso nel piano ${name}`}>
							{unlocked.map((f) => (
								<li key={f} className="flex items-center gap-2.5">
									<Check className="size-4 shrink-0 text-accent-fg" aria-hidden="true" />
									<span>{FeaturesDetails[f].name}</span>
								</li>
							))}
						</ul>
					)}
					<p className="mt-5 text-sm text-fg-muted">
						<span className="font-semibold text-fg">{formatPrice(plan.price, plan.currency)} al mese</span>
						{withTrial && <> · primi {TRIAL_DAYS} giorni gratis, senza carta</>} · disdici quando vuoi
					</p>
					<button type="button" onClick={upgrade} disabled={busy} className={cn('mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-accent px-6 font-semibold text-white transition-colors hover:bg-accent-hover disabled:cursor-wait disabled:opacity-60 focus-ring-offset', compact ? 'py-2.5 text-sm' : 'py-3.5')}>
						{busy ? (
							<>
								<Loader2 className="size-4 animate-spin" aria-hidden="true" />
								<span>Un attimo…</span>
							</>
						) : withTrial ? (
							`Prova ${name} gratis per ${TRIAL_DAYS} giorni`
						) : (
							`Attiva il piano ${name}`
						)}
					</button>
					{error && (
						<p className="mt-3 text-sm text-danger-fg" role="alert">
							{error}
						</p>
					)}
					<div className="mt-4 flex flex-col items-center gap-2 text-sm">
						<Link href="/pricing" className="rounded text-fg-muted underline underline-offset-2 hover:text-accent-fg focus-ring">
							Confronta tutti i piani
						</Link>
						{ready && !user && (
							<button type="button" onClick={() => openModal()} className="rounded text-fg-subtle hover:text-fg focus-ring">
								Hai già un abbonamento? Accedi
							</button>
						)}
					</div>
					{backUrl && (
						<Link href={backUrl} className="mt-5 inline-flex items-center gap-2 rounded text-sm text-fg-subtle hover:text-fg focus-ring">
							<ArrowLeft className="size-4" aria-hidden="true" />
							Torna alla teoria
						</Link>
					)}
				</section>
			</div>
		</div>
	);
}
