// src/components/shell/Header.tsx
'use client';

import { useCallback, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Menu, Search, UsersRound } from 'lucide-react';
import { CONTENT_ROOT, TUTORING_ROOT, ZAINO_ROOT } from '@/lib/config/site';
import { nodePath } from '@/lib/seo/slug';
import { useSearch } from '@/lib/state/search';
import { useAuth } from '@/lib/state/auth';
import type { ContentNode } from '@/lib/utils/tree';
import { cn } from '@/lib/utils/cn';
import { useContentTree } from './ContentTreeContext';
import { SearchField } from './SearchField';
import { SubjectMegaMenu } from './SubjectMegaMenu';
import { ThemeToggle } from './ThemeToggle';
import { LoginButton, LogoutButton } from './AuthButtons';
import { MobileMenu } from './MobileMenu';

const navLink = (active: boolean) => cn('rounded font-medium transition-colors focus-ring', active ? 'text-fg' : 'text-fg-muted hover:text-fg');

/**
 * Site header. Below `md` it is a phone bar: logo, a search field that
 * opens the overlay, and a menu button for everything else; the parent
 * can slide it away while the page scrolls down (`hidden`). From `md` up
 * it is the full desktop bar with the level menu and account buttons.
 * The level menu opens on hover, or on the down arrow from the keyboard
 * (never on focus alone), and it is rendered after the bar so Tab reaches it.
 */
export function Header({ hidden = false, immersive = false }: { hidden?: boolean; immersive?: boolean }) {
	const pathname = usePathname();
	const tree = useContentTree();
	const isActive = useSearch((s) => s.isActive);
	const activate = useSearch((s) => s.activate);
	const user = useAuth((s) => s.user);
	const [mega, setMega] = useState<{ level: ContentNode; keyboard: boolean } | null>(null);
	const [menuOpen, setMenuOpen] = useState(false);
	const megaMenu = tree.length > 0;
	const closeMega = () => setMega(null);
	const closeMenu = useCallback(() => setMenuOpen(false), []);
	const inMateriale = pathname.startsWith(CONTENT_ROOT);
	const inTutoring = pathname.startsWith(TUTORING_ROOT);
	const inZaino = pathname.startsWith(ZAINO_ROOT);

	return (
		<header
			onMouseLeave={closeMega}
			onKeyDown={(e) => e.key === 'Escape' && closeMega()}
			className={cn('sticky top-0 z-30 border-b border-edge bg-surface transition-transform duration-300 ease-out', hidden && 'max-md:-translate-y-full', immersive && 'max-md:hidden')}
		>
			<div id="site-header-bar" className="relative z-20 flex w-full items-center gap-2 bg-surface px-3 py-2 md:justify-between md:gap-4 md:p-3">
				<div className="flex min-w-0 items-center gap-2 md:gap-10">
					<Link href="/" className="flex shrink-0 items-center gap-3 rounded-md focus-ring" aria-label="Sapiens, pagina iniziale">
						{/* eslint-disable-next-line @next/next/no-img-element */}
						<img src="/favicon.svg" alt="" width={40} height={40} className="size-10 rounded-md" />
						<span className="hidden text-2xl font-semibold text-fg md:inline">Sapiens</span>
					</Link>

					{megaMenu && (
						<nav aria-label="Livelli didattici" className="hidden lg:block">
							<ul className="flex items-center justify-center gap-8">
								{tree.map((level) => {
									const open = mega?.level.id === level.id;
									return (
										<li key={level.id} className="relative">
											<Link
												href={nodePath([level])}
												onClick={closeMega}
												onMouseEnter={() => setMega({ level, keyboard: false })}
												onKeyDown={(e) => {
													if (e.key === 'ArrowDown') {
														e.preventDefault();
														setMega({ level, keyboard: true });
													}
												}}
												aria-haspopup="true"
												aria-expanded={open}
												aria-current={pathname === nodePath([level]) ? 'page' : undefined}
												className={cn('relative flex items-center gap-2', navLink(open))}
											>
												<span className="font-medium">{level.title}</span>
												<span className={cn('absolute -bottom-2 left-1/2 h-0.5 -translate-x-1/2 rounded-full bg-accent transition-all', open ? 'w-full opacity-100' : 'w-0 opacity-0')} aria-hidden="true" />
											</Link>
										</li>
									);
								})}
							</ul>
						</nav>
					)}

					{/* Tablets have no room for the level menu: the short links stand in for it until `lg`. */}
					<nav aria-label="Sezioni" className={cn('hidden items-center gap-6 whitespace-nowrap md:flex', megaMenu && 'lg:hidden xl:flex')}>
						<Link href={CONTENT_ROOT} aria-current={inMateriale ? 'page' : undefined} className={cn(navLink(inMateriale), megaMenu && 'lg:hidden')}>Materiale</Link>
						<Link href={TUTORING_ROOT} aria-current={inTutoring ? 'page' : undefined} className={navLink(inTutoring)}>Ripetizioni</Link>
						<Link href={ZAINO_ROOT} aria-current={inZaino ? 'page' : undefined} className={navLink(inZaino)}>Zaino</Link>
					</nav>
				</div>

				<div className="flex min-w-0 flex-1 items-center justify-end gap-2 md:flex-none md:gap-3">
					<div className="h-[40px] min-w-0 flex-1 md:h-auto md:w-64 md:flex-none lg:w-72 xl:w-96">
						{isActive ? (
							<div className="h-full w-full rounded-lg border border-transparent" aria-hidden="true" />
						) : (
							<div className="h-full">
								{/* Phones: a field-shaped button; the real input is in the overlay, where it gets the keyboard. */}
								<button type="button" onClick={activate} className="flex h-full w-full items-center gap-2 rounded-xl border border-edge bg-surface-2 px-3 text-left text-base text-fg-subtle active:bg-surface-3 focus-ring md:hidden" aria-label="Cerca su Sapiens">
									<Search className="size-5 shrink-0" aria-hidden="true" />
									<span className="truncate">Cerca su Sapiens</span>
								</button>
								<div className="hidden h-full md:block">
									<SearchField id="site-search" placeholder="Cerca su Sapiens" />
								</div>
							</div>
						)}
					</div>
					<Link href={TUTORING_ROOT} className="flex size-[44px] shrink-0 items-center justify-center rounded-xl border border-edge bg-surface-2 text-fg active:bg-surface-4 focus-ring md:hidden" aria-label="Ripetizioni" aria-current={inTutoring ? 'page' : undefined}>
						<UsersRound className="size-5" aria-hidden="true" />
					</Link>
					<div className="hidden items-center gap-3 md:flex">
						<ThemeToggle />
						<LoginButton />
						{user && <LogoutButton />}
					</div>
					<button type="button" onClick={() => setMenuOpen(true)} className="flex size-[44px] shrink-0 items-center justify-center rounded-xl border border-edge bg-surface-2 text-fg active:bg-surface-4 focus-ring md:hidden" aria-label="Apri il menu" aria-haspopup="dialog" aria-expanded={menuOpen}>
						<Menu className="size-6" aria-hidden="true" />
					</button>
				</div>
			</div>
			{mega && (
				<div className="absolute inset-x-0 z-10" style={{ top: 'var(--header-h, 64px)' }}>
					<SubjectMegaMenu level={mega.level} onClose={closeMega} autoFocus={mega.keyboard} />
				</div>
			)}
			<MobileMenu open={menuOpen} onClose={closeMenu} />
		</header>
	);
}

// src/lib/components/landing/Header.svelte
<script lang="ts">
	import { sendSearch, GLOBAL_SEARCH_KEY, HEADER_SEARCH_HEIGHT } from '$lib/animations/search-transition';
	import { searchStore } from '$lib/components/ui/search';
	import { page } from '$app/state';
	import { nodePath } from '$lib/seo/slug';
	import { CONTENT_ROOT, TUTORING_ROOT } from '$lib/config/site';
	import { Menu, Search } from 'lucide-svelte';
	import { authState } from '$lib/state/auth.svelte';
	import type { ContentNode } from '$lib/utils/tree';

	import ThemeToggle from '$lib/components/ui/theme/ThemeToggle.svelte';
	import Searchbar from '$lib/components/ui/Searchbar.svelte';
	import SubjectMegaMenu from '$lib/components/landing/SubjectMegaMenu.svelte';
	import LoginButton from '$lib/components/ui/buttons/LoginButton.svelte';
	import LogoutButton from '$lib/components/ui/buttons/LogoutButton.svelte';
	import MobileMenu from '$lib/components/landing/MobileMenu.svelte';

	/**
	 * Site header. Below `md` it is a phone bar: logo, a search field that
	 * opens the overlay, and a menu button for everything else; the parent
	 * can slide it away while the page scrolls down (`hidden`). From `md`
	 * up it is the full desktop bar with the level menu and account buttons.
	 */
	let {
		headerRef = $bindable(undefined),
		/** Slide the bar out of view (phones only). */
		hidden = false,
		/** Lesson pages on phones: no site header at all, the lesson has its own. */
		immersive = false
	} = $props();

	// The content tree is loaded only by the /materiale routes; other pages ship none of it.
	let tree = $derived((page.data.tree ?? []) as ContentNode[]);

	let hoveredLevel = $state<ContentNode | null>(null);
	let menuOpen = $state(false);

	function handleMenuMouseLeave(): void {
		hoveredLevel = null;
	}

	function handleKeydown(event: KeyboardEvent): void {
		if (event.key === 'Escape') hoveredLevel = null;
	}

	let isMegaMenuVisible = $derived(
		tree.length > 0 && (page.url.pathname.startsWith('/materiale') || page.url.pathname.startsWith('/admin'))
	);
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<header
	onmouseleave={handleMenuMouseLeave}
	onkeydown={handleKeydown}
	class="sticky top-0 z-30 bg-white dark:bg-zinc-900 border-b border-zinc-500/25 transition-transform duration-300 ease-out {hidden
		? 'max-md:-translate-y-full'
		: ''} {immersive ? 'max-md:hidden' : ''}"
>
	{#if hoveredLevel}
		<div
			class="absolute left-0 right-0 z-10"
			style="top: {headerRef?.offsetHeight || 0}px;"
		>
			<SubjectMegaMenu
				bind:level={hoveredLevel}
				columnsCount={5}
				topicsPerChapter={4}
			/>
		</div>
	{/if}

	<div
		bind:this={headerRef}
		class="relative z-20 flex w-full items-center gap-2 px-3 py-2 md:justify-between md:gap-4 md:p-3 bg-white dark:bg-zinc-900"
	>
		<div class="flex min-w-0 items-center gap-2 md:gap-10">
			<a
				href="/"
				class="flex shrink-0 items-center gap-3 rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500"
				aria-label="Sapiens, pagina iniziale"
			>
				<img src="/favicon.svg" alt="" width="40" height="40" class="size-10 rounded-md" />
				<span class="hidden md:inline text-2xl font-semibold text-zinc-900 dark:text-zinc-100">Sapiens</span>
			</a>

			{#if isMegaMenuVisible}
				<nav aria-label="Livelli didattici" class="hidden lg:block">
					<ul class="flex justify-center items-center gap-8">
						{#each tree as level (level.id)}
							<li class="relative">
								<a
									href={nodePath([level])}
									onclick={handleMenuMouseLeave}
									onmouseenter={() => (hoveredLevel = level)}
									onfocus={() => (hoveredLevel = level)}
									aria-haspopup="true"
									aria-expanded={hoveredLevel?.id === level.id}
									class="
										flex items-center gap-2 transition-colors duration-200 cursor-pointer relative rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500
										{hoveredLevel?.id === level.id ? 'text-zinc-900 dark:text-zinc-100' : 'text-zinc-600 dark:text-zinc-400'}
									"
								>
									<span class="font-medium">{level.title}</span>
									<span class="absolute -bottom-2 left-1/2 -translate-x-1/2 h-0.5 bg-crimson-500 rounded-full transition-all duration-200 {hoveredLevel?.id === level.id ? 'opacity-100 w-full' : 'opacity-0 w-0'}" aria-hidden="true"></span>
								</a>
							</li>
						{/each}
					</ul>
				</nav>
			{/if}

			<!-- Tablets have no room for the level menu: the short links stand in for it until `lg`. -->
			<nav aria-label="Sezioni" class="{isMegaMenuVisible ? 'hidden md:flex lg:hidden xl:flex' : 'hidden md:flex'} items-center gap-6 whitespace-nowrap">
				<a
					href={CONTENT_ROOT}
					class="{isMegaMenuVisible ? 'lg:hidden' : ''} font-medium transition-colors duration-200 rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500 {page.url.pathname.startsWith(CONTENT_ROOT) ? 'text-zinc-900 dark:text-zinc-100' : 'text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100'}"
				>
					Materiale
				</a>
				<a
					href={TUTORING_ROOT}
					aria-current={page.url.pathname.startsWith(TUTORING_ROOT) ? 'page' : undefined}
					class="font-medium transition-colors duration-200 rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500 {page.url.pathname.startsWith(TUTORING_ROOT) ? 'text-zinc-900 dark:text-zinc-100' : 'text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100'}"
				>
					Ripetizioni
				</a>
			</nav>
		</div>

		<div class="flex min-w-0 flex-1 items-center justify-end gap-2 md:flex-none md:gap-3">
			<div class="min-w-0 flex-1 md:flex-none md:w-64 lg:w-72 xl:w-96 h-[40px] md:h-auto" style="--search-h: {HEADER_SEARCH_HEIGHT}px;">
				{#if !$searchStore?.isActive}
					<div class="h-full md:h-[var(--search-h)]" out:sendSearch={{ key: GLOBAL_SEARCH_KEY }}>
						<!-- Phones: a field-shaped button; the real input is in the overlay, where it gets the keyboard. -->
						<button
							type="button"
							onclick={() => searchStore.activate()}
							class="md:hidden flex h-full w-full items-center gap-2 rounded-xl border border-zinc-500/25 bg-zinc-50 dark:bg-zinc-800 px-3 text-left text-base text-zinc-500 dark:text-zinc-400 active:bg-zinc-100 dark:active:bg-zinc-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500"
							aria-label="Cerca su Sapiens"
						>
							<Search class="size-5 shrink-0" aria-hidden="true" />
							<span class="truncate">Cerca su Sapiens</span>
						</button>
						<div class="hidden md:block h-full">
							<Searchbar
								placeholder="Cerca su Sapiens"
								hasKeyboardShortcut={false}
								width="w-full"
								size="md"
							/>
						</div>
					</div>
				{:else}
					<div
						class="h-full w-full rounded-lg border border-transparent"
						aria-hidden="true"
					></div>
				{/if}
			</div>

			<div class="hidden md:flex items-center gap-3">
				<ThemeToggle />
				<LoginButton />
				{#if authState.user}
					<LogoutButton />
				{/if}
			</div>

			<button
				type="button"
				onclick={() => (menuOpen = true)}
				class="md:hidden flex size-[44px] shrink-0 items-center justify-center rounded-xl border border-zinc-500/25 bg-zinc-50 dark:bg-zinc-800 text-zinc-800 dark:text-zinc-100 active:bg-zinc-200 dark:active:bg-zinc-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500"
				aria-label="Apri il menu"
				aria-haspopup="dialog"
				aria-expanded={menuOpen}
			>
				<Menu class="size-6" aria-hidden="true" />
			</button>
		</div>
	</div>
</header>

<MobileMenu bind:open={menuOpen} />
