// src/components/shell/SubjectMegaMenu.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Plus } from 'lucide-react';
import type { ContentNode } from '@/lib/utils/tree';
import { nodePath, plainTitle } from '@/lib/seo/slug';
import { cn } from '@/lib/utils/cn';

/** The level's subjects down the left, the hovered subject's chapters and first lessons across the right. Opened from the keyboard, the first subject takes focus. */
export function SubjectMegaMenu({ level, onClose, autoFocus = false, columns = 5, topicsPerChapter = 4 }: { level: ContentNode; onClose: () => void; autoFocus?: boolean; columns?: number; topicsPerChapter?: number }) {
	const [subject, setSubject] = useState<ContentNode | null>(level.children[0] ?? null);
	const [shownLevel, setShownLevel] = useState(level);
	const root = useRef<HTMLElement>(null);
	if (level !== shownLevel) {
		setShownLevel(level);
		setSubject(level.children[0] ?? null);
	}
	const chapters = subject?.children ?? [];
	useEffect(() => {
		if (autoFocus) root.current?.querySelector<HTMLElement>('a[href]')?.focus();
	}, [autoFocus, level]);

	return (
		<nav ref={root} className="max-h-[80vh] w-full animate-drop-in overflow-hidden border-b border-t border-edge bg-surface shadow-lg" aria-label={`Materie di ${level.title}`}>
			<div className="border-b border-edge bg-surface-2 px-8 py-5">
				<p className="text-xl font-semibold text-fg">{level.title}</p>
			</div>
			<div className="flex min-h-[400px] overflow-hidden">
				<div className="w-1/6 border-r border-edge bg-surface-2/50">
					{level.children.map((s) => (
						<Link
							key={s.id}
							href={nodePath([level, s])}
							onClick={onClose}
							onMouseEnter={() => setSubject(s)}
							onFocus={() => setSubject(s)}
							className={cn('flex w-full items-center gap-2 border-l-3 px-6 py-4 text-left text-base font-medium transition-all hover:bg-surface hover:text-accent-fg', subject?.id === s.id ? 'border-accent bg-surface text-accent-fg' : 'border-transparent text-fg-muted')}
						>
							{s.title}
						</Link>
					))}
				</div>
				<div className="h-full flex-1 overflow-y-auto p-8">
					{subject && (
						<div style={{ columnCount: columns, columnGap: '1.5rem' }}>
							{chapters.map((chapter, index) => {
								const topics = chapter.children;
								const shown = topics.length === topicsPerChapter + 1 ? topics : topics.slice(0, topicsPerChapter);
								return (
									<div key={chapter.id} className="mb-8 flex flex-col gap-4" style={{ breakInside: 'avoid' }}>
										<Link href={nodePath([level, subject, chapter])} onClick={onClose} className="group relative flex items-center gap-2 text-fg">
											<span className="line-clamp-1 font-semibold">{index + 1}. {plainTitle(chapter.title)}</span>
											<span className="absolute -bottom-2 left-1/2 h-0.5 w-0 -translate-x-1/2 rounded-full bg-accent opacity-0 transition-all group-hover:w-full group-hover:opacity-100" aria-hidden="true" />
										</Link>
										<div className="flex flex-col gap-1.5">
											{shown.map((topic) => (
												<Link key={topic.id} href={nodePath([level, subject, chapter, topic])} onClick={onClose} className="group rounded-lg py-1.5 ps-0 pe-3 text-sm transition-all hover:bg-surface-3 hover:ps-3">
													<span className="line-clamp-1 text-fg-muted group-hover:text-accent-fg">{plainTitle(topic.title)}</span>
												</Link>
											))}
											{topics.length > topicsPerChapter + 1 && (
												<Link href={nodePath([level, subject, chapter])} onClick={onClose} className="flex items-center py-1.5 text-xs text-fg-subtle hover:text-accent-fg">
													<Plus className="size-3" aria-hidden="true" />
													<span>{topics.length - topicsPerChapter} lezioni</span>
												</Link>
											)}
										</div>
									</div>
								);
							})}
						</div>
					)}
				</div>
			</div>
		</nav>
	);
}

// src/lib/components/landing/SubjectMegaMenu.svelte
<script lang="ts">
	import { fly, fade } from 'svelte/transition';
	import type { ContentNode } from '$lib/utils/tree';
	import { nodePath, plainTitle } from '$lib/seo/slug';
	import { Plus } from 'lucide-svelte';

	let {
		level = $bindable<ContentNode | null>(),
		columnsCount = 3,
		topicsPerChapter = 3
	} = $props();

	// Subjects are children of a level node
	let subjects = $derived(level?.children || []);
	let selectedSubject = $state<ContentNode | null>(null);

	// Auto-select first subject when level changes
	$effect(() => {
		selectedSubject = subjects.length > 0 ? subjects[0] : null;
	});

	function handleSubjectHover(subject: ContentNode): void {
		selectedSubject = subject;
	}

	function close(): void {
		level = null;
	}
</script>

{#if level}
<div
	class="w-full max-h-[80vh] overflow-hidden bg-white dark:bg-zinc-900 border-b border-t border-zinc-500/25 shadow-lg pointer-events-auto"
	aria-label="Materie di {level.title}"
	in:fly={{ y: -200, duration: 250, opacity: 0 }}
	out:fade={{ duration: 150 }}
>
	<div class="px-8 py-5 border-b border-zinc-500/25 bg-zinc-50 dark:bg-zinc-800/50">
		<div class="mx-auto flex items-center gap-3">
			<p class="text-xl font-semibold text-zinc-900 dark:text-zinc-100">
				{level.title}
			</p>
		</div>
	</div>

	<div class="mx-auto flex min-h-[400px] overflow-hidden">
		<div class="w-1/6 border-r border-zinc-500/25 bg-zinc-50/50 dark:bg-zinc-800/30">
			{#each subjects as subject (subject.id)}
				<a
					href={nodePath([level, subject])}
					onclick={close}
					onmouseenter={() => handleSubjectHover(subject)}
					onfocus={() => handleSubjectHover(subject)}
					class="
						w-full flex items-center gap-2 text-left px-6 py-4 text-base font-medium transition-all duration-200
						text-zinc-700 dark:text-zinc-300 hover:text-crimson-500 dark:hover:text-crimson-400
						hover:bg-white dark:hover:bg-zinc-800
							border-l-3
						{
							selectedSubject?.id === subject.id ?
								'bg-white dark:bg-zinc-800 border-crimson-500 dark:border-crimson-400 text-crimson-500 dark:text-crimson-400' :
								'border-transparent'
						}
					"
				>
					<span class="font-medium">{subject.title}</span>
				</a>
			{/each}
		</div>

		<div class="flex-1 p-8 overflow-y-auto h-full">
			{#if selectedSubject}
				{@const chapters = selectedSubject.children || []}
				<div class="gap-6 h-full" style="column-count: {columnsCount}; column-gap: 1.5rem; width: 100%;">
					{#each chapters as chapter, index (chapter.id)}
						{@const topics = chapter.children || []}
						<div class="flex flex-col gap-4 mb-8" style="break-inside: avoid;">
							<a
								href={nodePath([level, selectedSubject, chapter])}
								onclick={close}
								class="w-full flex items-center gap-2 text-left px-0 text-zinc-900 dark:text-zinc-100 transition-all duration-200 relative group"
							>
								<span class="font-semibold line-clamp-1">{index + 1}. {plainTitle(chapter.title)}</span>
								<span class="absolute -bottom-2 left-1/2 -translate-x-1/2 h-0.5 bg-crimson-500 rounded-full transition-all duration-200 opacity-0 w-0 group-hover:opacity-100 group-hover:w-full" aria-hidden="true"></span>
							</a>

							<div class="flex flex-col gap-1.5">
								{#each topics.slice(0, topicsPerChapter) as topic (topic.id)}
									<a
										href={nodePath([level, selectedSubject, chapter, topic])}
										onclick={close}
										class="w-full text-left px-3 ps-0 hover:ps-3 py-1.5 rounded-lg text-sm hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-all duration-200 group relative cursor-pointer"
									>
										<span class="text-zinc-600 dark:text-zinc-400 group-hover:text-crimson-500 dark:group-hover:text-crimson-400 line-clamp-1">{plainTitle(topic.title)}</span>
									</a>
								{/each}

								{#if topics.length == topicsPerChapter + 1}
									{@const topic = topics[topicsPerChapter]}
									<a
										href={nodePath([level, selectedSubject, chapter, topic])}
										onclick={close}
										class="w-full text-left px-3 ps-0 hover:ps-3 py-1.5 rounded-lg text-sm  hover:bg-zinc-100 dark:hover:bg-zinc-800  transition-all duration-200 group relative"
									>
										<span class="text-zinc-600 dark:text-zinc-400 group-hover:text-crimson-500 dark:group-hover:text-crimson-400 line-clamp-1">{plainTitle(topic.title)}</span>
									</a>
								{:else if topics.length > topicsPerChapter + 1}
									<a
										href={nodePath([level, selectedSubject, chapter])}
										onclick={close}
										class="w-full flex items-center text-left py-1.5 rounded-lg text-xs text-zinc-500 dark:text-zinc-500 hover:text-crimson-500 dark:hover:text-crimson-400 transition-all duration-200"
									>
										<Plus class="size-3" aria-hidden="true" />
										<span>{topics.length - topicsPerChapter} lezioni</span>
									</a>
								{/if}
							</div>
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>
{/if}
