// src/components/shell/ThemeToggle.tsx
'use client';

import { Moon, Sun } from 'lucide-react';
import { useTheme } from '@/lib/hooks/use-theme';

export function ThemeToggle() {
	const [theme, toggle] = useTheme();
	const dark = theme === 'dark';
	return (
		<button type="button" aria-label="Tema scuro" aria-pressed={dark} title={dark ? 'Passa al tema chiaro' : 'Passa al tema scuro'} onClick={toggle} className="relative flex items-center justify-center rounded-xl border border-edge bg-surface-2 p-2 hover:bg-surface-4 focus-ring-offset">
			<span className="relative flex size-5 items-center justify-center" aria-hidden="true">
				<Sun className="theme-toggle-icon absolute size-5 rotate-0 scale-100 text-fg-strong transition-all duration-200 dark:-rotate-90 dark:scale-0" />
				<Moon className="theme-toggle-icon absolute size-5 rotate-90 scale-0 text-fg-strong transition-all duration-200 dark:rotate-0 dark:scale-100" />
			</span>
		</button>
	);
}

// src/lib/components/theme/ThemeToggle.svelte
<script>
	import { Sun, Moon } from 'lucide-svelte';
	import { themeStore } from '$lib/components/theme/theme.js';

	const toggleTheme = () => {
		const newTheme = document.documentElement.classList.contains('dark') ? 'light' : 'dark';
		themeStore.setTheme(newTheme);
	}
</script>

<button 
	class="
		relative flex items-center justify-center p-2
		bg-zinc-50 dark:bg-zinc-800 border hover:bg-zinc-200 dark:hover:bg-zinc-700 
		border-zinc-200 dark:border-zinc-700
		rounded-xl transition-all duration-100 ease-in-out  cursor-pointer
	"
	onclick={toggleTheme}
>
	<div class="relative size-5 flex items-center justify-center">
		<Sun class="absolute theme-toggle-icon size-5 rotate-0 scale-100 transition-all duration-500 dark:-rotate-90 dark:scale-0 text-zinc-950 dark:text-zinc-50" />
		<Moon class="absolute theme-toggle-icon size-5 rotate-90 scale-0 transition-all duration-500 dark:rotate-0 dark:scale-100 text-zinc-950 dark:text-zinc-50" />
	</div>
</button>
