// src/components/shell/ThemeToggle.tsx
'use client';

import { Moon, Sun } from 'lucide-react';
import { useTheme } from '@/lib/hooks/use-theme';

export function ThemeToggle() {
	const [theme, toggle] = useTheme();
	const dark = theme === 'dark';
	return (
		<button type="button" aria-label="Tema scuro" aria-pressed={dark} title={dark ? 'Passa al tema chiaro' : 'Passa al tema scuro'} onClick={toggle} className="relative flex items-center justify-center rounded-xl border border-edge bg-surface-2 p-2 hover:bg-surface-4 focus-ring-offset">
			<span className="relative flex size-5 items-center justify-center" aria-hidden="true">
				<Sun className="theme-toggle-icon absolute size-5 rotate-0 scale-100 text-fg-strong transition-all duration-200 dark:-rotate-90 dark:scale-0" />
				<Moon className="theme-toggle-icon absolute size-5 rotate-90 scale-0 text-fg-strong transition-all duration-200 dark:rotate-0 dark:scale-100" />
			</span>
		</button>
	);
}

// src/lib/components/ui/theme/ThemeToggle.svelte
<script lang="ts">
	import { Sun, Moon } from 'lucide-svelte';
	import { themeStore } from '$lib/components/ui/theme/theme';

	const toggleTheme = (): void => {
		const newTheme: string = document.documentElement.classList.contains('dark') ? 'light' : 'dark';
		themeStore.setTheme(newTheme, true);
	}
</script>

<button
	type="button"
	aria-label="Cambia tema chiaro o scuro"
	class="
		relative flex items-center justify-center p-2
		bg-zinc-50 dark:bg-zinc-800 border hover:bg-zinc-200 dark:hover:bg-zinc-700
		border-zinc-500/25
		rounded-xl cursor-pointer
		focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-crimson-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-zinc-900
	"
	onclick={toggleTheme}
>
	<div class="relative size-5 flex items-center justify-center cursor-pointer" aria-hidden="true">
		<Sun class="theme-toggle-icon absolute size-5 rotate-0 scale-100 dark:-rotate-90 dark:scale-0 text-zinc-950 dark:text-zinc-50 transition-all duration-200 ease-in-out" />
		<Moon class="theme-toggle-icon absolute size-5 rotate-90 scale-0 dark:rotate-0 dark:scale-100 text-zinc-950 dark:text-zinc-50 transition-all duration-200 ease-in-out" />
	</div>
</button>
