// src/app/(site)/(account)/(tutor)/dashboard/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, BadgeCheck, CheckCircle2, Clock, Inbox, ShieldAlert, UserPen } from 'lucide-react';
import { TUTORING_ROOT } from '@/lib/config/site';
import { pageMetadata } from '@/lib/seo/page-metadata';
import { subjectName } from '@/lib/tutoring/config';
import { tutorArea } from '@/lib/server/tutor-area';
import { listTutorInbox, type TutorStatus } from '@/lib/server/tutoring-admin';
import type { IconComponent } from '@/lib/utils/icons';
import { Badge } from '@/components/ui/Badge';
import { Card, type CardTone } from '@/components/ui/Card';
import { LinkButton } from '@/components/ui/Button';
import { NoProfile } from '@/components/tutoring/NoProfile';

export const metadata: Metadata = pageMetadata({ title: 'Area tutor | Sapiens', path: '/dashboard' });

const STATUS: Record<TutorStatus, { icon: IconComponent; title: string; text: string; tone: CardTone }> = {
	draft: { icon: Clock, title: 'Bozza', text: 'Completa il profilo per inviarlo in revisione.', tone: 'default' },
	pending: { icon: Clock, title: 'In revisione', text: 'Controlliamo il profilo e ti avvisiamo via email quando è pubblico. Nel frattempo puoi ancora modificarlo.', tone: 'warn' },
	published: { icon: CheckCircle2, title: 'Pubblicato', text: 'Il profilo è visibile nella lista dei tutor. Le richieste degli studenti arrivano qui e via email.', tone: 'ok' },
	suspended: { icon: ShieldAlert, title: 'Sospeso', text: 'Il profilo non è visibile. Scrivici dalla pagina contatti per chiarire.', tone: 'danger' }
};

export default async function TutorDashboardPage() {
	const { tutor } = await tutorArea();
	if (!tutor) return <NoProfile title="Non hai ancora un profilo tutor" text="Racconta cosa insegni, a chi e dove: bastano cinque minuti. Il profilo va in revisione e poi compare nella lista." />;
	const inbox = await listTutorInbox(tutor.id);
	const pending = inbox.filter((r) => r.status === 'pending').length;
	const accepted = inbox.filter((r) => r.status === 'accepted').length;
	const status = STATUS[tutor.status];

	return (
		<>
			<h1 className="mb-6 text-3xl font-bold text-fg">Ciao {tutor.first_name}</h1>
			<div className="grid gap-5 lg:grid-cols-3">
				<Card as="section" tone={status.tone} className="p-6 lg:col-span-2" aria-labelledby="stato">
					<div className="flex items-start gap-3">
						<status.icon className="size-6 shrink-0 text-fg" aria-hidden="true" />
						<div className="space-y-1">
							<h2 id="stato" className="flex items-center gap-2 text-lg font-semibold text-fg">
								Profilo: {status.title}
								{tutor.verified && <Badge tone="info" icon={BadgeCheck}>Identità verificata</Badge>}
							</h2>
							<p className="text-sm text-fg-muted">{status.text}</p>
							{tutor.status === 'published' && (
								<Link href={`${TUTORING_ROOT}/${tutor.slug}`} className="inline-flex items-center gap-1 text-sm font-medium text-accent-fg hover:underline">
									Vedi il profilo pubblico <ArrowRight className="size-3.5" aria-hidden="true" />
								</Link>
							)}
						</div>
					</div>
				</Card>
				<Card as="section" className="p-6" aria-labelledby="richieste">
					<h2 id="richieste" className="mb-3 flex items-center gap-2 text-sm font-medium text-fg-subtle"><Inbox className="size-4" aria-hidden="true" /> Richieste</h2>
					<dl className="grid grid-cols-2 gap-4">
						{[['In attesa', pending], ['Accettate', accepted]].map(([label, n]) => (
							<div key={label}>
								<dt className="text-xs text-fg-subtle">{label}</dt>
								<dd className="text-3xl font-bold text-fg">{n}</dd>
							</div>
						))}
					</dl>
					<Link href="/leads" className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-accent-fg hover:underline">Apri le richieste <ArrowRight className="size-3.5" aria-hidden="true" /></Link>
				</Card>
				<Card as="section" className="p-6 lg:col-span-3" aria-labelledby="profilo">
					<div className="flex flex-wrap items-start justify-between gap-4">
						<div className="space-y-2">
							<h2 id="profilo" className="text-lg font-semibold text-fg">{tutor.first_name} {tutor.last_name.charAt(0)}. · {tutor.headline}</h2>
							<ul className="flex flex-wrap gap-2">
								{tutor.subjects.map((s) => <li key={s}><Badge>{subjectName(s)}</Badge></li>)}
							</ul>
						</div>
						<LinkButton href="/profile-editor" variant="secondary" size="sm">
							<UserPen className="size-4" aria-hidden="true" />
							Modifica il profilo
						</LinkButton>
					</div>
				</Card>
			</div>
		</>
	);
}

// src/routes/(app)/(tutor)/dashboard/+page.svelte
<script lang="ts">
	import { Clock, CheckCircle2, ShieldAlert, Inbox, UserPen, BadgeCheck, ArrowRight } from 'lucide-svelte';
	import { TUTORING_ROOT } from '$lib/config/site';
	import { subjectName } from '$lib/tutoring/config';

	import Seo from '$lib/components/seo/Seo.svelte';

	let { data } = $props();
	let tutor = $derived(data.tutor);
	let counts = $derived(data.counts);

	const STATUS = {
		draft: { icon: Clock, title: 'Bozza', text: 'Completa il profilo per inviarlo in revisione.', classes: 'border-zinc-300 bg-white dark:bg-zinc-950' },
		pending: { icon: Clock, title: 'In revisione', text: 'Controlliamo il profilo e ti avvisiamo via email quando è pubblico. Nel frattempo puoi ancora modificarlo.', classes: 'border-amber-200 bg-amber-50 dark:bg-amber-900/20 dark:border-amber-800' },
		published: { icon: CheckCircle2, title: 'Pubblicato', text: 'Il profilo è visibile nella lista dei tutor. Le richieste degli studenti arrivano qui e via email.', classes: 'border-emerald-200 bg-emerald-50 dark:bg-emerald-900/20 dark:border-emerald-800' },
		suspended: { icon: ShieldAlert, title: 'Sospeso', text: 'Il profilo non è visibile. Scrivici dalla pagina contatti per chiarire.', classes: 'border-red-200 bg-red-50 dark:bg-red-900/20 dark:border-red-800' }
	} as const;
</script>

<Seo title="Area tutor | Sapiens" path="/dashboard" noindex />

{#if !tutor}
	<section class="rounded-2xl border border-dashed border-zinc-500/30 bg-white dark:bg-zinc-950 p-8 text-center space-y-3">
		<UserPen class="size-10 mx-auto text-zinc-400" aria-hidden="true" />
		<h1 class="text-2xl font-bold text-zinc-900 dark:text-zinc-100">Non hai ancora un profilo tutor</h1>
		<p class="text-zinc-600 dark:text-zinc-400 max-w-md mx-auto">Racconta cosa insegni, a chi e dove: bastano cinque minuti. Il profilo va in revisione e poi compare nella lista.</p>
		<a href="/profile-editor" class="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-crimson-600 hover:bg-crimson-700 text-white font-semibold transition-colors">
			Crea il profilo
			<ArrowRight class="size-4" aria-hidden="true" />
		</a>
	</section>
{:else}
	{@const status = STATUS[tutor.status]}
	{@const StatusIcon = status.icon}
	<h1 class="text-3xl font-bold text-zinc-900 dark:text-zinc-100 mb-6">Ciao {tutor.first_name}</h1>

	<div class="grid lg:grid-cols-3 gap-5">
		<section class="lg:col-span-2 rounded-2xl border p-6 {status.classes}" aria-labelledby="stato">
			<div class="flex items-start gap-3">
				<StatusIcon class="size-6 shrink-0 text-zinc-700 dark:text-zinc-200" aria-hidden="true" />
				<div class="space-y-1">
					<h2 id="stato" class="text-lg font-semibold text-zinc-900 dark:text-zinc-100 flex items-center gap-2">
						Profilo: {status.title}
						{#if tutor.verified}
							<span class="inline-flex items-center gap-1 text-xs font-medium text-sky-700 dark:text-sky-300 bg-sky-50 dark:bg-sky-900/30 border border-sky-200 dark:border-sky-800 rounded-full px-2 py-0.5">
								<BadgeCheck class="size-3.5" aria-hidden="true" />
								Identità verificata
							</span>
						{/if}
					</h2>
					<p class="text-sm text-zinc-700 dark:text-zinc-300">{status.text}</p>
					{#if tutor.status === 'published'}
						<a href="{TUTORING_ROOT}/{tutor.slug}" class="inline-flex items-center gap-1 text-sm font-medium text-crimson-600 dark:text-crimson-400 hover:underline">Vedi il profilo pubblico <ArrowRight class="size-3.5" aria-hidden="true" /></a>
					{/if}
				</div>
			</div>
		</section>

		<section class="rounded-2xl border border-zinc-500/25 bg-white dark:bg-zinc-950 p-6" aria-labelledby="richieste">
			<h2 id="richieste" class="text-sm font-medium text-zinc-500 dark:text-zinc-400 mb-3 flex items-center gap-2"><Inbox class="size-4" aria-hidden="true" /> Richieste</h2>
			<dl class="grid grid-cols-2 gap-4">
				<div>
					<dt class="text-xs text-zinc-500 dark:text-zinc-400">In attesa</dt>
					<dd class="text-3xl font-bold text-zinc-900 dark:text-zinc-100">{counts.pending}</dd>
				</div>
				<div>
					<dt class="text-xs text-zinc-500 dark:text-zinc-400">Accettate</dt>
					<dd class="text-3xl font-bold text-zinc-900 dark:text-zinc-100">{counts.accepted}</dd>
				</div>
			</dl>
			<a href="/leads" class="mt-4 inline-flex items-center gap-1 text-sm font-medium text-crimson-600 dark:text-crimson-400 hover:underline">Apri le richieste <ArrowRight class="size-3.5" aria-hidden="true" /></a>
		</section>

		<section class="lg:col-span-3 rounded-2xl border border-zinc-500/25 bg-white dark:bg-zinc-950 p-6" aria-labelledby="profilo">
			<div class="flex flex-wrap items-start justify-between gap-4">
				<div class="space-y-2">
					<h2 id="profilo" class="text-lg font-semibold text-zinc-900 dark:text-zinc-100">{tutor.first_name} {tutor.last_name.charAt(0)}. · {tutor.headline}</h2>
					<ul class="flex flex-wrap gap-2">
						{#each tutor.subjects as s (s)}
							<li class="px-2.5 py-1 rounded-full text-xs font-medium bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300">{subjectName(s)}</li>
						{/each}
					</ul>
				</div>
				<a href="/profile-editor" class="inline-flex items-center gap-2 px-4 py-2 rounded-xl border border-zinc-500/25 text-sm font-medium text-zinc-800 dark:text-zinc-100 hover:border-crimson-300 dark:hover:border-crimson-800 transition-colors">
					<UserPen class="size-4" aria-hidden="true" />
					Modifica il profilo
				</a>
			</div>
		</section>
	</div>
{/if}
