// src/components/content/lesson/FloatingMenu.tsx
'use client';

import { useLayoutEffect, useRef, useState } from 'react';
import { contextualMenuPrompts, type Prompt } from '@/lib/data/prompts';
import { cn } from '@/lib/utils/cn';

export interface MenuPosition {
	x: number;
	y: number;
	/** The selection was made with a finger: the menu sits below it, as a two-column grid of large targets. */
	touch: boolean;
}

const MARGIN = 8;

/**
 * The actions offered on a text selection. With a mouse it floats above the
 * selection as one row; on touch it sits below the last selected line (the
 * OS callout takes the space above), kept inside the screen.
 */
export function FloatingMenu({ position, onSelect }: { position: MenuPosition | null; onSelect: (prompt: Prompt) => void }) {
	const box = useRef<HTMLDivElement>(null);
	const [width, setWidth] = useState(0);
	useLayoutEffect(() => {
		if (box.current) setWidth(box.current.offsetWidth);
	}, [position]);
	if (!position) return null;

	const half = width / 2;
	const left = Math.min(Math.max(position.x, MARGIN + half), Math.max(MARGIN + half, window.innerWidth - MARGIN - half));

	// The finger's selection is dropped before `click`, so the choice is taken on pointerdown.
	const choose = (e: React.SyntheticEvent, prompt: Prompt) => {
		e.preventDefault();
		window.getSelection()?.removeAllRanges();
		onSelect(prompt);
	};

	return (
		<div ref={box} className={cn('fixed z-50 max-w-[calc(100vw-16px)] -translate-x-1/2 animate-fade-in', !position.touch && '-translate-y-full')} style={{ top: position.y, left }} role="toolbar" aria-label="Chiedi a Sapiens AI">
			<div className={cn('rounded-2xl border border-accent-edge bg-surface/95 p-1.5 shadow-lg shadow-crimson-500/10 backdrop-blur-lg', position.touch ? 'grid grid-cols-[auto_auto] gap-1' : 'flex items-center gap-1')}>
				{contextualMenuPrompts.map((prompt) => (
					<button
						key={prompt.id}
						type="button"
						onPointerDown={(e) => position.touch && choose(e, prompt)}
						onClick={(e) => !position.touch && choose(e, prompt)}
						className={cn('flex items-center gap-2 whitespace-nowrap rounded-xl text-sm font-medium text-fg transition-colors hover:bg-accent-soft active:bg-accent-soft', position.touch ? 'min-h-[44px] px-3' : 'px-3 py-2')}
					>
						<prompt.icon className="size-4 shrink-0 text-accent-fg" aria-hidden="true" />
						<span>{prompt.label}</span>
					</button>
				))}
			</div>
			<div className={cn('absolute left-1/2 size-3 -translate-x-1/2 rotate-45 border-accent-edge bg-surface', position.touch ? '-top-1.5 border-l border-t' : '-bottom-1.5 border-b border-r')} style={position.touch ? { marginLeft: position.x - left } : undefined} aria-hidden="true" />
		</div>
	);
}

// src/lib/components/content/markdown/FloatingMenu.svelte
<script lang="ts">
    import { contextualMenuPrompts, type Prompt } from '$lib/data/prompts';

    /**
     * The actions offered on a text selection. With a mouse it floats above
     * the selection as one row; on touch it sits below the last selected
     * line (the OS callout takes the space above) as a two-column grid of
     * large targets, kept inside the screen.
     */
    let {
        isVisible = $bindable(false),
        position = $bindable({ x: 0, y: 0 }),
        touch = false,
        onSelect = $bindable((prompt: Prompt) => {}),
    } = $props();

    let menuWidth = $state(0);

    const MARGIN = 8;

    // Horizontal clamp so the menu never leaves the screen on a phone.
    let left = $derived.by(() => {
        if (typeof window === 'undefined') return position.x;
        const half = menuWidth / 2;
        const min = MARGIN + half;
        const max = window.innerWidth - MARGIN - half;
        return Math.min(Math.max(position.x, min), Math.max(min, max));
    });

    // The finger's selection is dropped before `click`, so the choice is taken on pointerdown.
    function choose(event: Event, prompt: Prompt) {
        event.preventDefault();
        window.getSelection()?.removeAllRanges();
        onSelect(prompt);
    }
</script>

{#if isVisible}
    <div
        bind:clientWidth={menuWidth}
		class="fixed z-50 -translate-x-1/2 animate-in fade-in zoom-in-95 duration-200 max-w-[calc(100vw-16px)] {touch ? '' : '-translate-y-full'}"
		style="top: {position.y}px; left: {left}px"
        role="toolbar"
        aria-label="Chiedi a Sapiens AI"
	>
		<div class="rounded-2xl p-1.5
			bg-white/95 dark:bg-zinc-900/95
			backdrop-blur-lg
			border border-crimson-200 dark:border-crimson-500/25
			shadow-lg shadow-crimson-500/10 dark:shadow-crimson-500/20
            {touch ? 'grid grid-cols-[auto_auto] gap-1' : 'flex items-center gap-1'}"
		>
			{#each Object.values(contextualMenuPrompts) as prompt}
				{@const Icon = prompt.icon}
			<button
                type="button"
                onpointerdown={(e) => touch && choose(e, prompt)}
                onclick={(e) => !touch && choose(e, prompt)}
                class="flex items-center gap-2 rounded-xl text-sm font-medium whitespace-nowrap
				text-zinc-700 dark:text-zinc-200
				hover:bg-crimson-50 dark:hover:bg-crimson-500/10 active:bg-crimson-50 dark:active:bg-crimson-500/10
				transition-colors {touch ? 'min-h-[44px] px-3' : 'px-3 py-2'}"
			>
					<Icon class="size-4 shrink-0 text-crimson-500" aria-hidden="true" />
					<span>{prompt.label}</span>
				</button>
			{/each}
		</div>

		<!-- Arrow -->
		<div class="absolute left-1/2 -translate-x-1/2 w-3 h-3 rotate-45 bg-white dark:bg-zinc-900 {touch
            ? '-top-1.5 border-l border-t'
            : '-bottom-1.5 border-r border-b'} border-crimson-200 dark:border-crimson-500/25"
            style={touch ? `margin-left: ${position.x - left}px` : ''}
            aria-hidden="true"
		></div>
    </div>
{/if}
